CREATE TABLE `wild_battlepet_zone_pool` (
	`Zone` INT(10) UNSIGNED NOT NULL,
	`Species` INT(10) UNSIGNED NOT NULL,
	`Replace` INT(10) UNSIGNED NOT NULL,
	`Max` INT(10) UNSIGNED NOT NULL,
	`RespawnTime` INT(10) UNSIGNED NOT NULL,
	`MinLevel` INT(10) UNSIGNED NOT NULL,
	`MaxLevel` INT(10) UNSIGNED NOT NULL,
	`Breed0` INT(10) UNSIGNED NOT NULL,
	`Breed1` INT(10) UNSIGNED NOT NULL,
	`Breed2` INT(10) UNSIGNED NOT NULL,
	`Breed3` INT(10) UNSIGNED NOT NULL,
	`Breed4` INT(10) UNSIGNED NOT NULL,
	`Breed5` INT(10) UNSIGNED NOT NULL,
	`Breed6` INT(10) UNSIGNED NOT NULL,
	`Breed7` INT(10) UNSIGNED NOT NULL,
	`Breed8` INT(10) UNSIGNED NOT NULL,
	`Breed9` INT(10) UNSIGNED NOT NULL
)
ENGINE=InnoDB;
