DELETE FROM spell_script_names WHERE ScriptName IN ('spell_pri_glyph_of_confession', 'spell_pri_confession');
INSERT INTO spell_script_names VALUES
(126152, 'spell_pri_glyph_of_confession'),
(126123, 'spell_pri_confession');

DELETE FROM trinity_string WHERE entry >= 14000 AND entry <= 14056;
INSERT INTO trinity_string (entry, content_default, content_loc2) VALUES
(14000, 'I always forget to gem my gear.', 'Je ne pense jamais à gemmer mon équipement.'),
(14001, 'I always wanted to be a paladin.', 'J''ai toujours voulu jouer paladin.'),
(14002, 'I ask for the Light to give me strength, but I''m not sure it really does.', 'Je demande à la Lumière de me donner la force, mais je ne sais pas trop si elle le fait vraiment.'),
(14003, 'I asked a friend for gold to buy my first mount.', 'Pour ma première monture, j''ai emprunté de l''or à un ami.'),
(14004, 'I dabble in archaeology, but I''m just not that interested in history.', 'Je touche un peu à l''archéologie, mais en fait, l''histoire ne m''intéresse pas vraiment.'),
(14005, 'I died to an elevator once. Maybe more than once.', 'Je suis mort en tombant d''un ascenseur, une fois. Peut-être même plus d''une fois.'),
(14006, 'I don''t know if Milhouse is a good guy or not.', 'Je n''arrive pas à savoir si Milhouse est un gentil ou un méchant.'),
(14007, 'I don''t really have a clue who the Sin''dorei are.', 'Je n''ai jamais vraiment compris qui sont les Sin''dorei.'),
(14008, 'I don''t really remember you in the mountains.', 'En fait, au sujet des montagnes... Je ne me souviens pas vraiment de vous.'),
(14009, 'I don''t treat all of my mounts equally..', 'Il m''arrive de maltraiter certaines de mes montures.'),
(14010, 'I fell off of Dalaran.', 'J''ai réussi à tomber de Dalaran.'),
(14011, 'I find all these names with so many apostrophes so confusing.', 'Tous ces noms remplis d''apostrophes, ça me donne mal au crâne.'),
(14012, 'I forgot the Sunwell.', 'J''ai oublié le Puits de soleil.'),
(14013, 'I go into dungeons not to make Azeroth a better place, but just for loot.', 'Je ne vais pas dans les donjons pour faire d''Azeroth un endroit meilleur. Seulement pour le butin.'),
(14014, 'I have "borrowed" things from my guild bank.', 'Il m''est arrivé d''« emprunter » du matériel dans mon coffre de guilde.'),
(14015, 'I have stood in the fire.', 'Je ne suis pas sorti du feu.'),
(14016, 'I haven''t been in a barber shop in months. Goblins with scissors. Shudder.', 'Je n''ai pas mis les pieds chez le coiffeur depuis des mois. Je veux dire, des gobelins avec des ciseaux... Je n''ai pas confiance.'),
(14017, 'I know he''s a jerk, but there''s something about Garrosh...', 'Je sais bien que c''est un sale type, mais il y a quelque chose chez Garrosh qui me...'),
(14018, 'I light things on fire and yell BY FIRE BE PURGED when nobody is looking.', 'Quand personne ne regarde, je mets le feu à des bouts de papier et je crie : « PAR LE FEU SOYEZ PURIFIÉS ! »'),
(14019, 'I never use the lightwell.', 'Je n''utilise jamais le puits de lumière.'),
(14020, 'I once punched a gnome. No reason. I was just having a bad day.', 'Une fois, j''ai frappé un gnome. Comme ça, sans raisons. J''étais juste de mauvaise humeur.'),
(14021, 'I once took a bow that a hunter wanted.', 'Une fois, j''ai pris l''arc qu''un chasseur voulait.'),
(14022, 'I outbid a friend on an auction for something I didn''t really want.', 'J''ai surenchéri sur un ami, alors que l''objet ne m''intéressait pas vraiment.'),
(14023, 'I really wasn''t prepared. Who knew?', 'Je n''étais pas prêt. Qui aurait pu l''être ?'),
(14024, 'I said I had been in the dungeon before, but i had no idea what I was doing. It was embarassing.', 'J''ai dit que je connaissais le donjon, mais je n''avais aucune idée de ce qu''il fallait faire. C''était... embarrassant.'),
(14025, 'I saw a mage cast a spell once and my jaw really did drop at the damage.', 'Une fois j''ai vu un mage lancer un sort, et j''ai vraiment été impressionné par les dégâts.'),
(14026, 'I sometimes forget if Northrend is north or south of here.', 'Il m''arrive d''oublier si le Norfendre est au nord ou au sud.'),
(14027, 'I sometimes use my mount to travel really short distances. I mean REALLY short.', 'Des fois, je prends ma monture pour une distance très courte. Je veux dire, vraiment très courte.'),
(14028, 'I sometimes wonder if tauren taste like... you know.', 'Des fois, je me demande si les taurens ont goût de... Enfin, vous voyez, quoi.'),
(14029, 'I spent six months chasing the Time-Lost Proto-Drake.', 'J''ai passé six mois à essayer d''avoir le proto-drake perdu dans le temps.'),
(14030, 'I thought pandaren were a type of furbolg.', 'Je croyais que les pandarens étaient une sorte de furbolgs.'),
(14031, 'I told my raid leader that I was ready, but I wasn''t really ready.', 'J''ai déjà dit au chef de raid que j''étais prêt alors que je ne l''étais pas.'),
(14032, 'I wasn''t really at the opening of Ahn''Qiraj, I just read about it.', 'En fait, je n''ai pas participé à l''ouverture des portes d''Ahn''Qiraj. J''ai juste lu le wiki.'),
(14033, 'I went into Alterac Valley and didn''t help my team at all.', 'Je suis allé à Alterac, et je n''ai rien fait pour mon équipe.'),
(14034, 'Oh, I took the candle.', 'J''ai... J''ai pris la bougie.'),
(14035, 'Sometimes I ask for a warlock to summon me when I''m really not that far away.', ' Des fois, je demande un TP démo alors que je ne suis pas très loin.'),
(14036, 'Sometimes when I''m questing, I want to be alone, so I pretend I can''t hear my friends.', 'Des fois, j''ai envie de faire mes quêtes tranquille, alors je fais semblant de ne pas entendre mes amis.'),
(14037, 'This is just a setback.', 'Tout ça n''est qu''un petit contretemps.'),
(14038, 'Troll toes sort of creep me out.', 'Les orteils des trolls me font un peu peur.'),
(14039, 'I inspect others to see if they are inspecting me.', 'J''inspecte les autres pour voir s''ils m''inspectent aussi.'),
(14040, 'I''m going to totally ninja that hunter''s loot.', 'Je vais carrément piquer le butin de ce chasseur.'),
(14041, 'I don''t use the strongest battle pets. Just the cutest ones.', 'Je n''utilise pas les mascottes les plus fortes, mais les plus jolies.'),
(14042, 'I still carry around Argent Crusade Scorugestones. You never know when they''ll be useful again.', 'J''ai toujours des pierres du Fléau de la Croisade d''argent sur moi. Elles pourraient encore servir.'),
(14043, 'I care more about transmogrification gear than upgrade gear.', 'Je me préoccupe plus de l''équipement de transmogrification que de l''équipement que je pourrais améliorer.'),
(14044, 'When my allies get mind controlled, I try really hard to kill them.', 'Quand mes alliés sont sous contrôle mental, je fais tout pour les tuer.'),
(14045, 'I always sell all of my old gear to the same vendor. Dude''s rich or something.', 'Je vends toujours mon équipement obsolète au même vendeur. Le gars doit être sacrément riche.'),
(14046, 'I get heart of the wild and the other heart of the wild confused.', 'Je me mélange toujours les pinceaux entre le coeur de fauve et le coeur de fauve. L''autre, évidemment.'),
(14047, 'When pandaren tell me to slooow doooown, I just want to punch them.', 'Quand un pandaren me demande de ralentir le rythme, il me donne envie de lui mettre mon poing dans la figure.'),
(14048, 'I always ask someone else how to reforge my gear.', 'Je demande toujours des conseils sur la façon de retoucher mon équipement.'),
(14049, 'I haven''t visited Sunsong Ranch in months. I can just imagine weeds and virmen everywhere.', 'Je ne me suis pas rendu à la ferme Chant du Soleil depuis des mois. Les lieux doivent être envahis de mauvaises herbes et de virmens.'),
(14050, 'I can''t decide between Horde and Alliance. Horde has goblin mages with quad-pigtails but Alliance has dwarf priests with twirly braids.', 'Je n''arrive pas à me décider entre la Horde et l''Alliance. Dans la Horde, il y a des gobelins mages à couettes. Mais l''Alliance a des nains prêtres à tresses.'),
(14051, 'I think one time I tried to kill Lei Shi instead of Lei Shen.', 'Je crois bien qu''une fois, j''ai essayé de tuer Lei Shi au lieu de Lei Shen.'),
(14052, 'I feel bad for my ground mounts. I hardly ever use them anymore.', 'Je suis un peu triste pour mes montures terrestres. Je ne les utilise presque plus.'),
(14053, 'With all these feathers, I thought that Medivh whas a druid.', 'Avec toutes ces plumes, je croyais que Medivh était un druide.'),
(14054, 'For a long time I thougt that the rogues really played with two fingers.', 'J''ai longtemps cru que les voleurs ne jouaient vraiment qu''avec deux doigts.'),
(14055, 'I never understood why draeneï females liked gnomes.', 'Je n''ai jamais compris ce que les femelles draeneï trouvaient aux gnomes.'),
(14056, ' confesses : ', ' se confesse : ');