DELETE FROM spell_script_names WHERE ScriptName IN ('spell_pri_glyph_of_confession', 'spell_pri_confession');
INSERT INTO spell_script_names VALUES
(126152, 'spell_pri_glyph_of_confession'),
(126123, 'spell_pri_confession');

DELETE FROM trinity_string WHERE entry >= 14000 AND entry <= 14056;
INSERT INTO trinity_string (entry, content_default, content_loc2, content_loc6) VALUES
(14000, 'I always forget to gem my gear.', 'Je ne pense jamais à gemmer mon équipement.', 'Siempre olvido engemar mi equipo.'),
(14001, 'I always wanted to be a paladin.', 'J''ai toujours voulu jouer paladin.', 'Siempre quise ser paladín.'),
(14002, 'I ask for the Light to give me strength, but I''m not sure it really does.', 'Je demande à la Lumière de me donner la force, mais je ne sais pas trop si elle le fait vraiment.', 'Le pido a la luz que me dé fuerzas, pero no sé si de verdad lo hace.'),
(14003, 'I asked a friend for gold to buy my first mount.', 'Pour ma première monture, j''ai emprunté de l''or à un ami.', 'Le he pedido oro a mi amigo para comprar mi primera montura..'),
(14004, 'I dabble in archaeology, but I''m just not that interested in history.', 'Je touche un peu à l''archéologie, mais en fait, l''histoire ne m''intéresse pas vraiment.', 'Hago un poco de arqueología, pero la verdad es que la historia no me interesa demasiado.'),
(14005, 'I died to an elevator once. Maybe more than once.', 'Je suis mort en tombant d''un ascenseur, une fois. Peut-être même plus d''une fois.', 'Me he muerto cayendo de un ascensor, una vez. O puede que más de una vez.'),
(14006, 'I don''t know if Milhouse is a good guy or not.', 'Je n''arrive pas à savoir si Milhouse est un gentil ou un méchant.', 'No consigo saber si Milhouse es un buen tipo o no.'),
(14007, 'I don''t really have a clue who the Sin''dorei are.', 'Je n''ai jamais vraiment compris qui sont les Sin''dorei.', 'Nunca llegué a entender quienes son los Sin''Dorei.'),
(14008, 'I don''t really remember you in the mountains.', 'En fait, au sujet des montagnes... Je ne me souviens pas vraiment de vous.', 'No te recuerdo con claridad en las montañas.'),
(14009, 'I don''t treat all of my mounts equally..', 'Il m''arrive de maltraiter certaines de mes montures.', 'No trato a todas mis monturas igualmente...'),
(14010, 'I fell off of Dalaran.', 'J''ai réussi à tomber de Dalaran.', 'Me he caído de Dalaran.'),
(14011, 'I find all these names with so many apostrophes so confusing.', 'Tous ces noms remplis d''apostrophes, ça me donne mal au crâne.', 'Todos esos nombres con apóstrofes me parecen muy raros.'),
(14012, 'I forgot the Sunwell.', 'J''ai oublié le Puits de soleil.', 'He olvidado la Fuente del Sol.'),
(14013, 'I go into dungeons not to make Azeroth a better place, but just for loot.', 'Je ne vais pas dans les donjons pour faire d''Azeroth un endroit meilleur. Seulement pour le butin.','No voy a las mazmorras para hacer de Azeroth un sitio mejor, solo busco objetos.'),
(14014, 'I have « borrowed » things from my guild bank.', 'Il m''est arrivé d''« emprunter » du matériel dans mon coffre de guilde.', 'He « tomado prestado » cosas del banco de hermandad.'),
(14015, 'I have stood in the fire.', 'Je ne suis pas sorti du feu.', 'Me he quedado atrapado en el fuego.'),
(14016, 'I haven''t been in a barber shop in months. Goblins with scissors. Shudder.', 'Je n''ai pas mis les pieds chez le coiffeur depuis des mois. Je veux dire, des gobelins avec des ciseaux... Je n''ai pas confiance.', 'No he ido a la peluquería en meses. Los goblins con tijeras no me inspiran confianza.'),
(14017, 'I know he''s a jerk, but there''s something about Garrosh...', 'Je sais bien que c''est un sale type, mais il y a quelque chose chez Garrosh qui me...', 'Sé que no es un buen tipo, pero hay algo en Garrosh que me...'),
(14018, 'I light things on fire and yell BY FIRE BE PURGED when nobody is looking.', 'Quand personne ne regarde, je mets le feu à des bouts de papier et je crie : « PAR LE FEU SOYEZ PURIFIÉS ! »', 'Cuando nadie me mira prendo fuego a las cosas y grito: « POR EL FUEGO SERÁ PURGADO »'),
(14019, 'I never use the lightwell.', 'Je n''utilise jamais le puits de lumière.', 'Yo nunca uso el pozo de luz.'),
(14020, 'I once punched a gnome. No reason. I was just having a bad day.', 'Une fois, j''ai frappé un gnome. Comme ça, sans raisons. J''étais juste de mauvaise humeur.', 'Una vez le pegué a un gnomo. Así, sin motivos. Simplemente estaba de mal humor.'),
(14021, 'I once took a bow that a hunter wanted.', 'Une fois, j''ai pris l''arc qu''un chasseur voulait.', 'Una vez cogí el arco que un cazador quería.'),
(14022, 'I outbid a friend on an auction for something I didn''t really want.', 'J''ai surenchéri sur un ami, alors que l''objet ne m''intéressait pas vraiment.', 'Yo superé la puja de un amigo en la subasta por algo que en realidad ni quería.'), 
(14023, 'I really wasn''t prepared. Who knew?', 'Je n''étais pas prêt. Qui aurait pu l''être ?', 'No estaba preparado. ¿Quién lo sabría?'),
(14024, 'I said I had been in the dungeon before, but i had no idea what I was doing. It was embarassing.', 'J''ai dit que je connaissais le donjon, mais je n''avais aucune idée de ce qu''il fallait faire. C''était... embarrassant.', 'Dije que conocía la mazmorra, pero en realidad no sabía que hacía… Fué vergonzoso.'),
(14025, 'I saw a mage cast a spell once and my jaw really did drop at the damage.', 'Une fois j''ai vu un mage lancer un sort, et j''ai vraiment été impressionné par les dégâts.', 'Ví a un mago tirar su hechizo y me quedé impresionado por el daño.'),
(14026, 'I sometimes forget if Northrend is north or south of here.', 'Il m''arrive d''oublier si le Norfendre est au nord ou au sud.', 'A veces olvido si Rasganorte está al norte o al sur.'),
(14027, 'I sometimes use my mount to travel really short distances. I mean REALLY short.', 'Des fois, je prends ma monture pour une distance très courte. Je veux dire, vraiment très courte.', 'A veces cojo mi montura para distancias cortas. Muy cortas.'), 
(14028, 'I sometimes wonder if tauren taste like... you know.', 'Des fois, je me demande si les taurens ont goût de... Enfin, vous voyez, quoi.', 'A veces, me pregunto si los tauren tienen sabor a… Bueno, ya sabéis que.'),
(14029, 'I spent six months chasing the Time-Lost Proto-Drake.', 'J''ai passé six mois à essayer d''avoir le proto-drake perdu dans le temps.', 'He pasado seis meses intentando conseguir el draco del tiempo perdido.'),
(14030, 'I thought pandaren were a type of furbolg.', 'Je croyais que les pandarens étaient une sorte de furbolgs.', 'Creía que los Pandaren eran una especie de Fúrbolgs. '),
(14031, 'I told my raid leader that I was ready, but I wasn''t really ready.', 'J''ai déjà dit au chef de raid que j''étais prêt alors que je ne l''étais pas.', 'Le he dicho al jefe de raid que estaba listo cuando no lo estaba.'),
(14032, 'I wasn''t really at the opening of Ahn''Qiraj, I just read about it.', 'En fait, je n''ai pas participé à l''ouverture des portes d''Ahn''Qiraj. J''ai juste lu le wiki.', 'En realidad no estuve durante la apertura de Ahn’’Qiraj. Tan solo leí acerca de ella.'),
(14033, 'I went into Alterac Valley and didn''t help my team at all.', 'Je suis allé à Alterac, et je n''ai rien fait pour mon équipe.', 'Fui al Valle de Alterac y no ayudé del todo a mi equipo.'),
(14034, 'Oh, I took the candle.', 'J''ai... J''ai pris la bougie.', 'Oh, cogí la vela.'),
(14035, 'Sometimes I ask for a warlock to summon me when I''m really not that far away.', ' Des fois, je demande un TP démo alors que je ne suis pas très loin.', 'A veces pido a un brujo que me sumonee cuando en realidad no estoy tan lejos.'),
(14036, 'Sometimes when I''m questing, I want to be alone, so I pretend I can''t hear my friends.', 'Des fois, j''ai envie de faire mes quêtes tranquille, alors je fais semblant de ne pas entendre mes amis.', 'A veces me apetece hacer misiones tranquilo, así que hago como si no escuchase a mis amigos.'),
(14037, 'This is just a setback.', 'Tout ça n''est qu''un petit contretemps.', 'Todo esto es solo un pequeño contratiempo.'),
(14038, 'Troll toes sort of creep me out.', 'Les orteils des trolls me font un peu peur.', 'Los pies de los trolls me dan miedo.'),
(14039, 'I inspect others to see if they are inspecting me.', 'J''inspecte les autres pour voir s''ils m''inspectent aussi.', 'Inspecciono a los demás para ver si me inspeccionan a mí.'),
(14040, 'I''m going to totally ninja that hunter''s loot.', 'Je vais carrément piquer le butin de ce chasseur.', 'Me voy a quedar con el botín de ese cazador.'),
(14041, 'I don''t use the strongest battle pets. Just the cutest ones.', 'Je n''utilise pas les mascottes les plus fortes, mais les plus jolies.', 'No utilizo las mascotas más fuertes, si no las más bonitas.'),
(14042, 'I still carry around Argent Crusade Scorugestones. You never know when they''ll be useful again.', 'J''ai toujours des pierres du Fléau de la Croisade d''argent sur moi. Elles pourraient encore servir.', 'Siempre tengo Piedras de Plaga de la cruzada argenta sobre mi. Podrían servir aún.'),
(14043, 'I care more about transmogrification gear than upgrade gear.', 'Je me préoccupe plus de l''équipement de transmogrification que de l''équipement que je pourrais améliorer.', 'Me preocupo más por la transfiguración que de actualizar mi equipo. '),
(14044, 'When my allies get mind controlled, I try really hard to kill them.', 'Quand mes alliés sont sous contrôle mental, je fais tout pour les tuer.', 'Cuando mis aliados controlaron mi mente, Intenté matarlos.'),
(14045, 'I always sell all of my old gear to the same vendor. Dude''s rich or something.', 'Je vends toujours mon équipement obsolète au même vendeur. Le gars doit être sacrément riche.', 'Siempre vendo mi equipo al mismo vendedor. El tipo debe ser muy rico.'),
(14046, 'I get heart of the wild and the other heart of the wild confused.', 'Je me mélange toujours les pinceaux entre le cœur de fauve et le cœur de fauve. L''autre, évidemment.', 'Me sale el corazón de la selva y el otro corazón de la naturaleza confusa.'),
(14047, 'When pandaren tell me to slooow doooown, I just want to punch them.', 'Quand un pandaren me demande de ralentir le rythme, il me donne envie de lui mettre mon poing dans la figure.', 'Cuando el panda me pide que corra máaaas despaaaaacio, me dan ganas de meterle un puñetazo en la cara.'),
(14048, 'I always ask someone else how to reforge my gear.', 'Je demande toujours des conseils sur la façon de retoucher mon équipement.', 'Siempre pido consejo sobre como retocar mi equipo.'),
(14049, 'I haven''t visited Sunsong Ranch in months. I can just imagine weeds and virmen everywhere.', 'Je ne me suis pas rendu à la ferme Chant du Soleil depuis des mois. Les lieux doivent être envahis de mauvaises herbes et de virmens.', 'No he visitado la granja Canto de Sol desde hace meses. Ya puedo imaginarme la zona llena de hierbas y plantas por todas partes.'),
(14050, 'I can''t decide between Horde and Alliance. Horde has goblin mages with quad-pigtails but Alliance has dwarf priests with twirly braids.', 'Je n''arrive pas à me décider entre la Horde et l''Alliance. Dans la Horde, il y a des gobelins mages à couettes. Mais l''Alliance a des nains prêtres à tresses.', 'No puedo decidirme entre horda o alianza. ¡La horda tiene goblins magos con coletas, pero la alianza tiene enanos sacerdotes con trenzas!'),
(14051, 'I think one time I tried to kill Lei Shi instead of Lei Shen.', 'Je crois bien qu''une fois, j''ai essayé de tuer Lei Shi au lieu de Lei Shen.', 'Creo que una vez intenté matar a Lei Shi en lugar de Lei Shen.'),
(14052, 'I feel bad for my ground mounts. I hardly ever use them anymore.', 'Je suis un peu triste pour mes montures terrestres. Je ne les utilise presque plus.', 'Me siento mal por mis monturas terrestres. A duras penas las volví a usar.'),
(14053, 'With all these feathers, I thought that Medivh was a druid.', 'Avec toutes ces plumes, je croyais que Medivh était un druide.', 'Con todas esas plumas, pensé que Medivh era una druida.'),
(14054, 'For a long time I thougt that the rogues really played with two fingers.', 'J''ai longtemps cru que les voleurs ne jouaient vraiment qu''avec deux doigts.', 'Durante mucho tiempo realmente creí que los pícaros jugaban con dos dedos.'),
(14055, 'I never understood why draeneï females liked gnomes.', 'Je n''ai jamais compris ce que les femelles draeneï trouvaient aux gnomes.', 'Nunca entendí por qué las draeneis se sienten atraídas por los gnomos.'),
(14056, ' confesses : ', ' se confesse : ', ' confiesa : ');