DELETE FROM spell_script_names WHERE scriptName IN ("spell_sha_lava_burst");
INSERT INTO spell_script_names VALUES
(51505, "spell_sha_lava_burst");
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_blackout_kick';
INSERT INTO `spell_script_names` VALUES ('100784', 'spell_monk_blackout_kick');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_rising_sun_kick';
INSERT INTO `spell_script_names` VALUES ('107428', 'spell_monk_rising_sun_kick');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_keg_smash';
INSERT INTO `spell_script_names` VALUES ('121253', 'spell_monk_keg_smash');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_jab';
INSERT INTO `spell_script_names` VALUES ('100780', 'spell_monk_jab');
INSERT INTO `spell_script_names` VALUES ('108557', 'spell_monk_jab');
INSERT INTO `spell_script_names` VALUES ('115698', 'spell_monk_jab');
INSERT INTO `spell_script_names` VALUES ('115687', 'spell_monk_jab');
INSERT INTO `spell_script_names` VALUES ('115693', 'spell_monk_jab');
INSERT INTO `spell_script_names` VALUES ('115695', 'spell_monk_jab');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_pal_word_of_glory_heal';
INSERT INTO `spell_script_names` VALUES ('130551', 'spell_pal_word_of_glory_heal');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_pal_word_of_glory_damage';
INSERT INTO `spell_script_names` VALUES ('130552', 'spell_pal_word_of_glory_damage');