DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_retenless_strikes';
INSERT INTO `spell_script_names` VALUES (408, 'spell_rog_retenless_strikes');
INSERT INTO `spell_script_names` VALUES (2098, 'spell_rog_retenless_strikes');
INSERT INTO `spell_script_names` VALUES (73651, 'spell_rog_retenless_strikes');
INSERT INTO `spell_script_names` VALUES (5171, 'spell_rog_retenless_strikes');
INSERT INTO `spell_script_names` VALUES (26679, 'spell_rog_retenless_strikes');
INSERT INTO `spell_script_names` VALUES (1943, 'spell_rog_retenless_strikes');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_retenless_strikes_proc';
INSERT INTO `spell_script_names` VALUES (14181, 'spell_rog_retenless_strikes_proc');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_combo_point_delayed';
INSERT INTO `spell_script_names` VALUES (139569, 'spell_rog_combo_point_delayed');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_mage_unstable_magic';
INSERT INTO `spell_script_names` VALUES (30451, 'spell_mage_unstable_magic');
INSERT INTO `spell_script_names` VALUES (133, 'spell_mage_unstable_magic');
INSERT INTO `spell_script_names` VALUES (116, 'spell_mage_unstable_magic');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_mage_ice_lance';
INSERT INTO `spell_script_names` VALUES (30455, 'spell_mage_ice_lance');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_warr_execute';
INSERT INTO `spell_script_names` VALUES (163201, 'spell_warr_execute');
