INSERT INTO areatrigger_template (`spell_id`, `eff_index`, `entry`, `scale_x`, `scale_y`, `flags`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`) VALUES(161511, 0, 6857, 1, 1, 16384, 12000, 0, 0, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `spell_id` = VALUES(`spell_id`), `eff_index` = VALUES(`eff_index`), `entry` = VALUES(`entry`), `scale_x` = VALUES(`scale_x`), `scale_y` = VALUES(`scale_y`), `flags` = VALUES(`flags`), `data0` = VALUES(`data0`), `data1` = VALUES(`data1`), `data2` = VALUES(`data2`), `data3` = VALUES(`data3`), `data4` = VALUES(`data4`), `data5` = VALUES(`data5`), `data6` = VALUES(`data6`), `data7` = VALUES(`data7`);

-- INSERT INTO areatrigger_move_template (`path_size`, `duration`) VALUES(4, 12000) ON DUPLICATE KEY UPDATE `path_size` = VALUES(`path_size`), `duration` = VALUES(`duration`);

-- INSERT INTO areatrigger_move_splines (`path_id`, `path_x`, `path_y`, `path_z`) VALUES(0, 0, -0.4477539, 0) ON DUPLICATE KEY UPDATE `path_id` = VALUES(`path_id`), `path_x` = VALUES(`path_x`), `path_y` = VALUES(`path_y`), `path_z` = VALUES(`path_z`);
-- INSERT INTO areatrigger_move_splines (`path_id`, `path_x`, `path_y`, `path_z`) VALUES(1, 0, -0.4477539, 0) ON DUPLICATE KEY UPDATE `path_id` = VALUES(`path_id`), `path_x` = VALUES(`path_x`), `path_y` = VALUES(`path_y`), `path_z` = VALUES(`path_z`);
-- INSERT INTO areatrigger_move_splines (`path_id`, `path_x`, `path_y`, `path_z`) VALUES(2, 0, 27.40308, 0) ON DUPLICATE KEY UPDATE `path_id` = VALUES(`path_id`), `path_x` = VALUES(`path_x`), `path_y` = VALUES(`path_y`), `path_z` = VALUES(`path_z`);
-- INSERT INTO areatrigger_move_splines (`path_id`, `path_x`, `path_y`, `path_z`) VALUES(3, 0, 27.40308, 0) ON DUPLICATE KEY UPDATE `path_id` = VALUES(`path_id`), `path_x` = VALUES(`path_x`), `path_y` = VALUES(`path_y`), `path_z` = VALUES(`path_z`);

INSERT INTO areatrigger_template (`spell_id`, `eff_index`, `entry`, `scale_x`, `scale_y`, `flags`, `morph_curve_id`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`) VALUES(161467, 0, 6852, 0.01, 5, 16514, 763, 0, 0, 0, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `spell_id` = VALUES(`spell_id`), `eff_index` = VALUES(`eff_index`), `entry` = VALUES(`entry`), `scale_x` = VALUES(`scale_x`), `scale_y` = VALUES(`scale_y`), `flags` = VALUES(`flags`), `morph_curve_id` = VALUES(`morph_curve_id`), `data0` = VALUES(`data0`), `data1` = VALUES(`data1`), `data2` = VALUES(`data2`), `data3` = VALUES(`data3`), `data4` = VALUES(`data4`), `data5` = VALUES(`data5`), `data6` = VALUES(`data6`), `data7` = VALUES(`data7`);

INSERT INTO areatrigger_template (`spell_id`, `eff_index`, `entry`, `scale_x`, `scale_y`, `flags`, `morph_curve_id`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`) VALUES(161465, 0, 6852, 0.01, 5, 16514, 763, 0, 0, 0, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `spell_id` = VALUES(`spell_id`), `eff_index` = VALUES(`eff_index`), `entry` = VALUES(`entry`), `scale_x` = VALUES(`scale_x`), `scale_y` = VALUES(`scale_y`), `flags` = VALUES(`flags`), `morph_curve_id` = VALUES(`morph_curve_id`), `data0` = VALUES(`data0`), `data1` = VALUES(`data1`), `data2` = VALUES(`data2`), `data3` = VALUES(`data3`), `data4` = VALUES(`data4`), `data5` = VALUES(`data5`), `data6` = VALUES(`data6`), `data7` = VALUES(`data7`);

INSERT INTO areatrigger_template (`spell_id`, `eff_index`, `entry`, `scale_x`, `scale_y`, `flags`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`) VALUES(152280, 0, 6212, 8, 8, 16384, 0, 0, 0, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `spell_id` = VALUES(`spell_id`), `eff_index` = VALUES(`eff_index`), `entry` = VALUES(`entry`), `scale_x` = VALUES(`scale_x`), `scale_y` = VALUES(`scale_y`), `flags` = VALUES(`flags`), `data0` = VALUES(`data0`), `data1` = VALUES(`data1`), `data2` = VALUES(`data2`), `data3` = VALUES(`data3`), `data4` = VALUES(`data4`), `data5` = VALUES(`data5`), `data6` = VALUES(`data6`), `data7` = VALUES(`data7`);

INSERT INTO areatrigger_template (`spell_id`, `eff_index`, `entry`, `scale_x`, `scale_y`, `flags`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`) VALUES(82938, 0, 6094, 1, 1, 8192, 5, 5, 5, 5, 1, 1, 0, 0) ON DUPLICATE KEY UPDATE `spell_id` = VALUES(`spell_id`), `eff_index` = VALUES(`eff_index`), `entry` = VALUES(`entry`), `scale_x` = VALUES(`scale_x`), `scale_y` = VALUES(`scale_y`), `flags` = VALUES(`flags`), `data0` = VALUES(`data0`), `data1` = VALUES(`data1`), `data2` = VALUES(`data2`), `data3` = VALUES(`data3`), `data4` = VALUES(`data4`), `data5` = VALUES(`data5`), `data6` = VALUES(`data6`), `data7` = VALUES(`data7`);

INSERT INTO areatrigger_template (`spell_id`, `eff_index`, `entry`, `scale_x`, `scale_y`, `flags`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`) VALUES(76577, 0, 5742, 1, 1, 8192, 8, 8, 4, 4, 1, 1, 0, 0) ON DUPLICATE KEY UPDATE `spell_id` = VALUES(`spell_id`), `eff_index` = VALUES(`eff_index`), `entry` = VALUES(`entry`), `scale_x` = VALUES(`scale_x`), `scale_y` = VALUES(`scale_y`), `flags` = VALUES(`flags`), `data0` = VALUES(`data0`), `data1` = VALUES(`data1`), `data2` = VALUES(`data2`), `data3` = VALUES(`data3`), `data4` = VALUES(`data4`), `data5` = VALUES(`data5`), `data6` = VALUES(`data6`), `data7` = VALUES(`data7`);

INSERT INTO areatrigger_template (`spell_id`, `eff_index`, `entry`, `scale_x`, `scale_y`, `flags`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`) VALUES(48505, 0, 0, 30, 30, 16388, 0, 0, 0, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `spell_id` = VALUES(`spell_id`), `eff_index` = VALUES(`eff_index`), `entry` = VALUES(`entry`), `scale_x` = VALUES(`scale_x`), `scale_y` = VALUES(`scale_y`), `flags` = VALUES(`flags`), `data0` = VALUES(`data0`), `data1` = VALUES(`data1`), `data2` = VALUES(`data2`), `data3` = VALUES(`data3`), `data4` = VALUES(`data4`), `data5` = VALUES(`data5`), `data6` = VALUES(`data6`), `data7` = VALUES(`data7`);