DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_brewmaster_training_tiger_palm';
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_fists_of_fury';
INSERT INTO `spell_script_names` VALUES (113656, 'spell_monk_fists_of_fury');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_jab';
INSERT INTO `spell_script_names` VALUES (100780, 'spell_monk_jab');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_monk_tiger_palm';
INSERT INTO `spell_script_names` VALUES (100787, 'spell_monk_tiger_palm');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_pal_hammer_of_wrath';
INSERT INTO `spell_script_names` VALUES ('158392', 'spell_pal_hammer_of_wrath');
INSERT INTO `spell_script_names` VALUES ('24275', 'spell_pal_hammer_of_wrath');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_pri_shadow_word_pain';
INSERT INTO `spell_script_names` VALUES ('589', 'spell_pri_shadow_word_pain');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_hun_glyph_of_animal_bond';
INSERT INTO `spell_script_names` VALUES ('20895', 'spell_hun_glyph_of_animal_bond');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_hun_bombardment';
INSERT INTO `spell_script_names` VALUES ('35110', 'spell_hun_bombardment');