DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dru_ferocious_bite';
INSERT INTO `spell_script_names` VALUES (22568, 'spell_dru_ferocious_bite');
INSERT INTO `spell_script_names` VALUES (157496, 'spell_pal_hammer_of_wrath');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_shadow_focus';
INSERT INTO `spell_script_names` VALUES (108209, 'spell_rog_shadow_focus');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_burst_of_speed';
INSERT INTO `spell_script_names` VALUES (108212, 'spell_rog_burst_of_speed');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_internal_bleeding';
INSERT INTO `spell_script_names` VALUES (408, 'spell_rog_internal_bleeding');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_smoke_bomb';
INSERT INTO `spell_script_names` VALUES (76577, 'spell_rog_smoke_bomb');
DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_rog_fan_of_knives';
INSERT INTO `spell_script_names` VALUES (51723, 'spell_rog_fan_of_knives');