DELETE FROM script_texts WHERE script_texts.`npc_entry` IN (86238, 76266);
INSERT INTO script_texts VALUES ('86238', '-1603202', 'I will slice the flesh from your bones!', '', 'J\'arracherai la chair de vos os !', 'Euch filetiere ich!', '', '', '¡Os arrancaré la carne de los huesos!', ' ¡Os arrancaré la carne de los huesos!', 'Я срежу плоть с ваших костей!', '', '', '43887', '1', '0', '0', 'Ranjit combat start');
INSERT INTO script_texts VALUES ('86238', '-1603203', 'I... perish....', '', 'Je… m\'éteins…', 'Ich... scheide dahin...', '', '', 'Yo... perezco...', 'Yo... perezco...', 'Я... умираю...', '', '', '43888', '1', '0', '0', 'Ranjit just died');
INSERT INTO script_texts VALUES ('86238', '-1603204', 'You cannot outrun the wind!', '', 'Tu ne peux distancer le vent !', 'Niemand läuft dem Wind davon!', '', '', '¡No pueden huir del viento!', '¡No pueden huir del viento!', 'Нельзя перегнать ветер!', '', '', '43892', '1', '0', '0', 'Ranjit four winds');
INSERT INTO script_texts VALUES ('86238', '-1603205', 'Your doom is coming!', '', 'C\'est ta perte qui court à toi.', 'Euer Untergang naht.', '', '', 'Vuestro fin se acerca.', 'Vuestro fin se acerca.', 'Погибель близка.', '', '', '43891', '1', '0', '0', 'Ranjit four winds');
INSERT INTO script_texts VALUES ('86238', '-1603206', 'We will feed you corpse to the Kaliri!', '', 'Votre cadavre sera jeté en pâture aux kaliris !', 'Die Kaliri werden sich an Euren toten Körpern laben!', '', '', '¡Te daremos de comer a los kaliri!', '¡Te daremos de comer a los kaliri!', 'Мы скормим ваши тела калири!', '', '', '43889', '1', '0', '0', 'Ranjit kill 1');
INSERT INTO script_texts VALUES ('86238', '-1603207', 'Move faster ground dweller!', '', 'Tu n\'es pas assez rapide, créature aptère !', 'Schneller, Bodenbewohner!', '', '', '¡Más rápido, terrestre!', '¡Más rápido, terrestre!', 'Слишком медленно, червяк!', '', '', '43889', '1', '0', '0', 'Ranjit kill 2');
INSERT INTO script_texts VALUES ('86238', '-1603208', 'As long as we rule the sky, none should oppose us!', '', 'Tant que nous régnerons sur le ciel, personne ne pourra nous défier !', 'Solange wir die Himmel beherrschen, widersetzt sich uns niemand!', '', '', '', '', 'Пока мы царим в небесах, никто не угроза для нас!', '', '', '43893', '1', '0', '0', 'Ranjit victory');

INSERT INTO script_texts VALUES ('76266', '-1603209', 'We will cast you down like the mongrels you are!', '', 'Nous allons vous abattre comme les bâtards que vous êtes !', 'Euch Bastarde werden wir in die Tiefe stürzen!', '', '', '¡Os aniquilaremos como los perros que sois!', '¡Os aniquilaremos como los perros que sois!', 'Мы сбросим вас вниз, пресмыкающиеся!', '', '', '45176', '1', '0', '0', 'Viryx combat start');
INSERT INTO script_texts VALUES ('76266', '-1603210', 'We will always... soar....', '', 'Nous nous élèverons… toujours…', 'Wir werden immer... auf Euch hinabsehen...', '', '', 'Nosotros siempre... volaremos...', 'Nosotros siempre... volaremos...', 'Мы всегда будем… парить…', '', '', '45177', '1', '0', '0', 'Viryx just died');
INSERT INTO script_texts VALUES ('76266', '-1603211', 'Cast them down, let the scavengers below feed on their pulp!', '', 'Jetez-les dans le vide, que les charognards se repaissent de leur dépouille !', 'Stoßt sie hinab. Sollen sich die Aasfresser an Ihren Eingeweiden gütlich tun!', '', '', '¡Láncenlos, que los carroñeros de abajo se alimenten con su pulpa!', '¡Láncenlos, que los carroñeros de abajo se alimenten con su pulpa!', 'Они рухнут на землю, и стервятники склюют их плоть!', '', '', '45180', '1', '0', '0', 'Viryx cast down');
INSERT INTO script_texts VALUES ('76266', '-1603212', 'Servants, protect your master!', '', 'Serviteurs, protégez votre maître !', 'Diener, beschützt Euren Herrn!', '', '', 'Sirvientes, ¡protejan a su maestra!', 'Sirvientes, ¡protejan a su maestra!', 'Слуги, защищайте хозяина!', '', '', '45181', '1', '0', '0', 'Viryx call adds');
INSERT INTO script_texts VALUES ('76266', '-1603216', 'Behold the might, of the Arakkoa!', '', 'Soyez témoins de la puissance des arakkoa !', 'Werdet Zeuge der Macht der Arakkoa!', '', '', '¡Contemplen el poder de los arakkoa!', '¡Contemplen el poder de los arakkoa!', 'Узрите мощь араккоа!', '', '', '45182', '1', '0', '0', 'Viryx lens flare');
INSERT INTO script_texts VALUES ('76266', '-1603213', 'You are unfit to rise to this hight, return to your filth below!', '', 'Vous n\'êtes pas dignes de vous élever à cette hauteur, retournez dans la fange qui vous sert d\'habitat !', 'Ihr seid es nicht wert, auf diese Höhen aufzusteigen. Kehrt in den Dreck zurück!', '', '', '', '', 'Тебе не дано подняться на пик, возвращайся обратно в грязь!', '', '', '45178', '1', '0', '0', 'Viryx kill 1');
INSERT INTO script_texts VALUES ('76266', '-1603214', 'What funny little birds... you have no wings!', '', 'Que voilà de drôles de volatiles ! Ils sont dépourvus d’ailes !', 'Ihr seltsamen kleinen Vögel. Wo sind denn Eure Flügel?', '', '', '', '', 'Какие странные птички – совсем без крыльев!', '', '', '45179', '1', '0', '0', 'Viryx kill 2');
INSERT INTO script_texts VALUES ('76266', '-1603215', 'As long as we rule the sky, you will always be beneath us!', '', 'Tant que nous régnerons sur le ciel, vous nous serez toujours inférieurs !', 'Solange wir die Himmel beherrschen, seid Ihr uns niemals ebenbürtig!', '', '', '', '', 'Пока мы царим в небесах, вы всегда будете ниже нас!', '', '', '45183', '1', '0', '0', 'Viryx victory');

REPLACE INTO trinity_string VALUES ('14061', '|TInterface\Icons\inv_elemental_crystal_fire.blp:20|tYou have been targeted with |cFFFF0000|Hspell:160282|h[Solar Detonation]|h|r! Move away from your allies!', '', '', '', '', '', '', '', '', '', '');