create table `instance_encounters` (
	`entry` int (10),
	`creditType` tinyint (3),
	`creditEntry` int (10),
	`lastEncounterDungeon` smallint (5),
	`comment` varchar (765)
); 
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('201','0','18371','0','Shirrak the Dead Watcher');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('202','0','18373','149','Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('203','0','18341','0','Pandemonius');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('204','0','18343','0','Tavarok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('205','0','18344','148','Nexus-Prince Shaffar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('206','0','18472','0','Darkweaver Syth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('207','0','18473','150','Talon King Ikiss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('208','0','18731','0','Ambassador Hellmaw');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('209','0','18667','0','Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('210','0','18732','0','Grandmaster Vorpil');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('211','0','18708','151','Murmur');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('212','0','29309','0','Elder Nadox');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('213','0','29308','0','Prince Taldaram');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('214','0','29310','0','Jedoga Shadowseeker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('215','0','29311','218','Herald Volazj');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('216','0','28684','0','Krik\'thir the Gatewatcher');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('217','0','28921','0','Hadronox');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('218','0','29120','204','Anub\'arak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('219','0','4887','0','Ghamoo-ra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('220','0','4831','0','Lady Sarevess');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('221','0','6243','0','Gelihast');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('222','0','12902','0','Lorgus Jett');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('224','0','4830','0','Old Serra\'kis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('225','0','4832','0','Twilight Lord Kelris');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('226','0','4829','10','Aku\'mai');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('227','0','9018','30','High Interrogator Gerstahn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('228','0','9025','0','Lord Roccor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('229','0','9319','0','Houndmaster Grebmar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('230','0','10096','0','Ring of Law');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('231','0','9024','0','Pyromancer Loregrain');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('232','0','9017','0','Lord Incendius');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('233','0','9041','0','Warder Stilgiss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('234','0','9056','0','Fineous Darkvire');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('235','0','9016','0','Bael\'Gar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('236','0','9033','0','General Angerforge');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('237','0','8983','0','Golem Lord Argelmach');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('238','0','9537','0','Hurley Blackbreath');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('239','0','9502','0','Phalanx');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('240','0','9543','0','Ribbly Screwspigot');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('241','0','9499','0','Plugger Spazzring');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('242','0','9156','0','Ambassador Flamelash');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('243','0','9035','0','The Seven');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('244','0','9938','0','Magmus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('245','0','9019','276','Emperor Dagran Thaurissan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('246','0','18371','0','Shirrak the Dead Watcher');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','18373','178','Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('248','0','18341','0','Pandemonius');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('249','0','18343','0','Tavarok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('250','0','22930','0','Yor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('251','0','18344','179','Nexus-Prince Shaffar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('252','0','18472','0','Darkweaver Syth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('253','0','23035','0','Anzu');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('254','0','18473','180','Talon King Ikiss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('255','0','18731','0','Ambassador Hellmaw');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','18667','0','Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('257','0','18732','0','Grandmaster Vorpil');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('258','0','18708','181','Murmur');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('259','0','29309','0','Elder Nadox');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('260','0','29308','0','Prince Taldaram');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('261','0','29310','0','Jedoga Shadowseeker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('262','0','30258','0','Amanitar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('263','0','29311','219','Herald Volazj');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('264','0','28684','0','Krik\'thir the Gatewatcher');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('265','0','28921','0','Hadronox');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('266','0','29120','241','Anub\'arak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('267','0','9196','0','Highlord Omokk');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('268','0','9236','0','Shadow Hunter Vosh\'gajin');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('269','0','9237','0','War Master Voone');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('270','0','10596','0','Mother Smolderweb');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('271','0','10584','0','Urok Doomhowl');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('272','0','9736','0','Quartermaster Zigris');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('273','0','10268','0','Gizrul the Slavener');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('274','0','10220','0','Halycon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('275','0','9568','32','Overlord Wyrmthalak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('276','0','9816','0','Pyroguard Emberseer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('277','0','10264','0','Solakar Flamewreath');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('278','0','10429','0','Warchief Rend Blackhand');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('279','0','10430','0','The Beast');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('280','0','10363','0','General Drakkisath');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('281','0','18096','170','Epoch Hunter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('282','0','18096','183','Epoch Hunter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('283','0','17862','0','Captain Skarloc');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('284','0','17862','0','Captain Skarloc');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('285','0','17848','0','Lieutenant Drake');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('286','0','17848','0','Lieutenant Drake');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('287','0','17879','0','Chrono Lord Deja');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('288','0','17879','0','Chrono Lord Deja');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('289','0','17880','0','Temporus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('290','0','17880','0','Temporus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('291','0','17881','171','Aeonus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('292','0','17881','182','Aeonus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('293','0','26529','0','Meathook');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('294','0','26530','0','Salram the Fleshcrafter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('295','0','26532','0','Chrono-Lord Epoch');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('296','1','58630','0','Mal\'ganis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('297','0','26529','0','Meathook');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('298','0','26530','0','Salram the Fleshcrafter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('299','0','26532','0','Chrono-Lord Epoch');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('300','1','58630','0','Mal\'ganis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('301','0','17941','0','Mennu the Betrayer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('302','0','17991','0','Rokmar the Crackler');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('303','0','17942','140','Quagmirran');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('304','0','17941','0','Mennu the Betrayer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('305','0','17991','0','Rokmar the Crackler');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('306','0','17942','184','Quagmirran');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('314','0','17797','0','Hydromancer Thespia');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('315','0','17797','0','Hydromancer Thespia');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('316','0','17796','0','Mekgineer Steamrigger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('317','0','17796','0','Mekgineer Steamrigger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('318','0','17798','147','Warlord Kalithresh');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('319','0','17798','185','Warlord Kalithresh');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('320','0','17770','0','Hungarfen');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('321','0','17770','0','Hungarfen');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('322','0','18105','0','Ghaz\'an');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('323','0','18105','0','Ghaz\'an');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('329','0','17826','0','Swamplord Musel\'ek');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('330','0','17826','0','Swamplord Musel\'ek');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('331','0','17882','146','The Black Stalker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('332','0','17882','186','The Black Stalker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('334','1','68572','0','Grand Champions');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('336','1','68572','0','Grand Champions');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('338','1','68574','0','Argent Champion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('339','1','68574','0','Argent Champion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('340','1','68663','245','The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('341','1','68663','249','The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('343','0','11490','0','Zevrim Thornhoof');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('344','0','13280','0','Hydrospawn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('345','0','14327','0','Lethtendris');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('346','0','11492','34','Alzzin the Wildshaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('347','0','11488','0','Illyanna Ravenoak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('348','0','11487','0','Magister Kalendris');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('349','0','11496','0','Immol\'thar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('350','0','11489','0','Tendris Warpwood');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('361','0','11486','36','Prince Tortheldrin');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('362','0','14326','0','Guard Mol\'dar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('363','0','14322','0','Stomper Kreeg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('364','0','14321','0','Guard Fengus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('365','0','14323','0','Guard Slip\'kik');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('366','0','14325','0','Captain Kromcrush');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('367','0','14324','0','Cho\'Rush the Observer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('368','0','11501','38','King Gordok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('369','0','26630','0','Trollgore');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('370','0','26630','0','Trollgore');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('371','0','26631','0','Novos the Summoner');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('372','0','26631','0','Novos the Summoner');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('373','0','27483','0','King Dred');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('374','0','27483','0','King Dred');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('375','1','61863','214','The Prophet Tharon\'ja');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('376','1','61863','215','The Prophet Tharon\'ja');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('378','0','7079','0','Viscous Fallout');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('379','0','7361','0','Grubbis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('380','0','6235','0','Electrocutioner 6000');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('381','0','6229','0','Crowd Pummeler 9-60');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('382','0','7800','14','Mekgineer Thermaplugg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('383','0','29304','0','Slad\'ran');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('384','0','29304','0','Slad\'ran');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('385','0','29573','0','Drakkari Colossus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('386','0','29573','0','Drakkari Colossus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('387','0','29305','0','Moorabi');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('388','0','29305','0','Moorabi');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('389','0','29932','0','Eck the Ferocious');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('390','0','29306','216','Gal\'darah');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('391','0','29306','217','Gal\'darah');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('392','0','17306','0','Watchkeeper Gargolmar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('393','0','17306','0','Watchkeeper Gargolmar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('394','0','17308','0','Omor the Unscarred');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('395','0','17308','0','Omor the Unscarred');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('396','0','17537','136','Vazruden the Herald');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('397','0','17537','188','Vazruden the Herald');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('401','0','17381','0','The Maker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('402','0','17381','0','The Maker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('403','0','17380','0','Broggok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('404','0','17380','0','Broggok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('405','0','17377','137','Keli\'dan the Breaker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('406','0','17377','187','Keli\'dan the Breaker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('407','0','16807','0','Grand Warlock Nethekurse');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('408','0','16807','0','Grand Warlock Nethekurse');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('409','0','20923','0','Blood Guard Porung');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('410','0','16809','0','Warbringer O\'mrogg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('411','0','16809','0','Warbringer O\'mrogg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('412','0','16808','138','Warchief Kargath Bladefist');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('413','0','16808','189','Warchief Kargath Bladefist');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('414','0','24723','0','Selin Fireheart');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('415','0','24723','0','Selin Fireheart');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('416','0','24744','0','Vexallus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('417','0','24744','0','Vexallus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('418','0','24560','0','Priestess Delrissa');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('419','0','24560','0','Priestess Delrissa');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('420','0','24664','198','Kael\'thas Sunstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('421','0','24664','201','Kael\'thas Sunstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('422','0','13282','0','Noxxion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('423','0','12258','26','Razorlash');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('424','0','12236','272','Lord Vyletongue');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('425','0','12225','0','Celebras the Cursed');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('426','0','12203','0','Landslide');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('427','0','13601','0','Tinkerer Gizlock');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('428','0','13596','0','Rotgrip');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('429','0','12201','273','Princess Theradras');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('430','0','11517','0','Oggleflint');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('431','0','11520','4','Taragaman the Hungerer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('432','0','11518','0','Jergosh the Invoker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('433','0','11519','0','Bazzalan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('434','0','7355','0','Tuten\'kash');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('435','0','7357','0','Mordresh Fire Eye');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('436','0','8567','0','Glutton');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('437','0','7358','20','Amnennar the Coldbringer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('438','0','6168','0','Roogug');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('439','0','4424','0','Aggem Thorncurse');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('440','0','4428','0','Death Speaker Jargba');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('441','0','4420','0','Overlord Ramtusk');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('443','0','4421','16','Charlga Razorflank');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('444','0','3983','0','Interrogator Vishas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('445','0','4543','18','Bloodmage Thalnos');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('446','0','3974','0','Houndmaster Loksey');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('447','0','6487','165','Arcanist Doan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('448','0','3975','163','Herod');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('449','0','4542','0','High Inquisitor Fairbanks');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('450','0','3977','164','High Inquisitor Whitemane');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('451','0','10506','0','Kirtonos the Herald');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('452','0','10503','0','Jandice Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('453','0','11622','0','Rattlegore');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('454','0','10433','0','Marduk Blackpool');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('455','0','10432','0','Vectus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('456','0','10508','0','Ras Frostwhisper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('457','0','10505','0','Instructor Malicia');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('458','0','11261','0','Doctor Theolen Krastinov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('459','0','10901','0','Lorekeeper Polkelt');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('460','0','10507','0','The Ravenian');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('461','0','10504','0','Lord Alexei Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('462','0','10502','0','Lady Illucia Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('463','0','1853','2','Darkmaster Gandling');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('472','0','10516','0','The Unforgiven');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('473','0','10558','0','Hearthsinger Forresten');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('474','0','10808','0','Timmy the Cruel');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('475','0','10997','0','Willey Hopebreaker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('476','0','11032','0','Commander Malor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('477','0','10811','0','Instructor Galford');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('478','0','10813','40','Balnazzar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('479','0','10436','0','Baroness Anastari');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('480','0','10437','0','Nerub\'enkan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('481','0','10438','0','Maleki the Pallid');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('482','0','10435','0','Magistrate Barthilas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('483','0','10439','0','Ramstein the Gorger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('484','0','10440','274','Lord Aurius Rivendare');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('486','0','5721','0','Dreamscythe');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('487','0','5720','0','Weaver');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('488','0','5710','0','Jammal\'an the Prophet');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('490','0','5719','0','Morphaz');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('491','0','5722','0','Hazzas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('492','0','8443','0','Avatar of Hakkar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('493','0','5709','28','Shade of Eranikus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('494','0','20870','0','Zereketh the Unbound');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('495','0','20870','0','Zereketh the Unbound');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('496','0','20885','0','Dalliah the Doomsayer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('497','0','20885','0','Dalliah the Doomsayer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('498','0','20886','0','Wrath-Scryer Soccothrates');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('499','0','20886','0','Wrath-Scryer Soccothrates');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('500','0','20912','174','Harbinger Skyriss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('501','0','20912','190','Harbinger Skyriss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('502','0','17976','0','Commander Sarannis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('504','0','17976','0','Commander Sarannis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('505','0','17975','0','High Botanist Freywinn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('506','0','17975','0','High Botanist Freywinn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('507','0','17978','0','Thorngrin the Tender');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('508','0','17978','0','Thorngrin the Tender');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('509','0','17980','0','Laj');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('510','0','17980','0','Laj');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('511','0','17977','173','Warp Splinter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('512','0','17977','191','Warp Splinter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('513','0','19219','0','Mechano-Lord Capacitus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('514','0','19219','0','Mechano-Lord Capacitus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('515','0','19221','0','Nethermancer Sepethrea');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('516','0','19221','0','Nethermancer Sepethrea');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('517','0','19220','172','Pathaleon the Calculator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('518','0','19220','192','Pathaleon the Calculator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('519','0','26796','0','Frozen Commander');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('520','0','26731','0','Grand Magus Telestra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('521','0','26731','0','Grand Magus Telestra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('522','0','26763','0','Anomalus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('523','0','26763','0','Anomalus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('524','0','26794','0','Ormorok the Tree-Shaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('525','0','26794','0','Ormrok the Tree-Shaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('526','0','26723','225','Keristrasza');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('527','0','26723','226','Keristrasza');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('528','0','27654','0','Drakos the Interrogator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('529','0','27654','0','Drakos the Interrogator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('530','0','27447','0','Varos Cloudstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('531','0','27447','0','Varos Cloudstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('532','0','27655','0','Mage-Lord Urom');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('533','0','27655','0','Mage-Lord Urom');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('534','0','27656','206','Ley-Guardian Eregos');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('535','0','27656','211','Ley-Guardian Eregos');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('541','0','29315','0','First Prisoner');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('542','0','29315','0','First Prisoner');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('543','0','29316','0','Second Prisoner');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('544','0','29316','0','Second Prisoner');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('545','0','31134','220','Cyanigosa');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('546','0','31134','221','Cyanigosa');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('547','0','6910','0','Revelosh');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('548','0','6906','0','The Lost Dwarves');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('549','0','7228','0','Ironaya');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('551','0','7206','0','Ancient Stone Keeper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('552','0','7291','0','Galgann Firehammer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('553','0','4854','0','Grimlok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('554','0','2748','22','Archaedas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('555','0','28586','0','General Bjarngrim');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('556','0','28586','0','General Bjarngrim');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('557','0','28587','0','Volkhan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('558','0','28587','0','Volkhan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('559','0','28546','0','Ionar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('560','0','28546','0','Ionar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('561','0','28923','207','Loken');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('562','0','28923','212','Loken');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('563','0','27977','0','Krystallus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('564','0','27977','0','Krystallus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('565','0','27975','0','Maiden of Grief');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('566','0','27975','0','Maiden of Grief');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('567','1','59046','0','Tribunal of Ages');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('568','1','59046','0','Tribunal of Ages');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('569','0','27978','208','Sjonnir the Ironshaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('570','0','27978','213','Sjonnir the Ironshaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('571','0','23953','0','Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','23953','0','Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('573','0','24201','0','Skarvold & Dalronn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('574','0','24201','0','Skarvold & Dalronn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('575','0','23954','202','Ingvar the Plunderer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('576','0','23954','242','Ingvar the Plunderer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('577','0','26668','0','Svala Sorrowgrave');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('578','0','26668','0','Svala Sorrowgrave');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('579','0','26687','0','Gortok Palehoof');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('580','0','26687','0','Gortok Palehoof');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('581','0','26693','0','Skadi the Ruthless');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('582','0','26693','0','Skadi the Ruthless');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('583','0','26861','203','King Ymiron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('584','0','26861','205','King Ymiron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('585','0','3671','0','Lady Anacondra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('586','0','3669','0','Lord Cobrahn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('587','0','3653','0','Kresh');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('588','0','3670','0','Lord Pythas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('589','0','3674','0','Skum');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('590','0','3673','0','Lord Serpentis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('591','0','5775','0','Verdan the Everliving');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('592','0','3654','1','Mutanus the Devourer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('593','0','7795','0','Hydromancer Velratha');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('594','0','7273','0','Ghaz\'rilla');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('595','0','8127','0','Antu\'sul');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('596','0','7272','0','Theka the Martyr');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('597','0','7271','0','Witch Doctor Zum\'rah');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('598','0','7796','0','Nekrum Gutchewer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('599','0','7275','0','Shadowpriest Sezz\'ziz');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('600','0','7267','24','Chief Ukorz Sandscalp');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('601','0','22887','0','High Warlord Naj\'entus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('602','0','22898','0','Supremus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('603','0','22841','0','Shade of Akama');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('604','0','22871','0','Teron Gorefiend');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('605','0','22948','0','Gurtogg Bloodboil');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('606','0','23420','0','Reliquary of Souls');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('607','0','22947','0','Mother Shahraz');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('608','0','23426','0','The Illidari Council');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('609','0','22917','196','Illidan Stormrage');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('610','0','12435','0','Razorgore the Untamed');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('611','0','13020','0','Vaelastrasz the Corrupt');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('612','0','12017','0','Broodlord Lashlayer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('613','0','11983','0','Firemaw');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('614','0','14601','0','Ebonroc');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('615','0','11981','0','Flamegor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('616','0','14020','0','Chromaggus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('617','0','11583','50','Nefarian');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('618','0','17767','0','Rage Winterchill');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('619','0','17808','0','Anetheron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('620','0','17888','0','Kaz\'rogal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('621','0','17842','0','Azgalor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('622','0','17968','195','Archimonde');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('623','0','21216','0','Hydross the Unstable');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('624','0','21217','0','The Lurker Below');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('625','0','21215','0','Leotheras the Blind');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('626','0','21214','0','Fathom-Lord Karathress');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('627','0','21213','0','Morogrim Tidewalker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('628','0','21212','194','Lady Vashj');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('649','0','18831','0','High King Maulgar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('650','0','19044','177','Gruul the Dragonkiller');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('651','0','17257','176','Magtheridon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('652','0','15550','0','Attumen the Huntsman');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('653','0','15687','0','Moroes');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('654','0','16457','0','Maiden of the Virtue');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('655','0','16812','0','Opera Event');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('656','0','15691','0','The Curator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('657','0','15688','0','Terestian Illhoof');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('658','0','16524','0','Shade of Aran');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('659','0','15689','0','Netherspite');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('660','0','22520','0','Chess Event');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('661','0','15690','175','Prince Malchezaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('662','0','17225','0','Nightbane');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('663','0','12118','0','Lucifron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('664','0','11982','0','Magmadar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('665','0','12259','0','Gehennas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('666','0','12057','0','Garr');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('667','0','12264','0','Shazzrah');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('668','0','12056','0','Baron Geddon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('669','0','12098','0','Sulfuron Harbinger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('670','0','11988','0','Golemagg the Incinerator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('671','0','12018','0','Majordomo Executus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('672','0','11502','48','Ragnaros');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1442','0','67231','0','L\'epreuve du roi');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1509','0','61243','467','Gekkan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1510','0','61243','519','Gekkan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1441','0','61398','0','Xin le maitre d\'arme');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1409','0','0','0','Protecteurs de l\'eternel //TODO ADD BUNNY');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1505','0','62983','0','Lei shi');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1431','0','60999','535','Sha de la peur');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1422','0','59303','163','Maitre chien Braun');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1421','0','58632','0','Maitre d\'armes Harlan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1420','0','59150','0','Tisseur de flammes Koegler');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1423','0','59789','0','Thalnos le déchiqueteur d\'âmes');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1424','0','59223','0','Frère Korloff');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1425','0','3977','474','Grande inquisitrice Blanchetête');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1426','0','58633','0','Instructrice Froidecoeur');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1427','0','59184','0','Jandice Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1428','0','59153','0','Cliquettripes');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1429','0','59200','0','Lilian Voss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1430','0','59080','472','Sombre Maitre Gandling');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1395','0','60089','0','Le garde de pierre - bunny');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1390','0','60009','0','Feng le maudit');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1434','0','60143','531','Garaljal le lieur d\'esprit');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1407','0','0','0','Volonté de l\'empereur //todo bunny');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1507','0','62980','0','Vizir Imperial Zor\'lok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1504','0','62543','0','Seigneur des lames');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1463','0','62164','0','Garalon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1498','0','62397','0','Seigneur du vent');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1499','0','62511','0','Sculpte ambre');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1501','0','62837','533','Grande impératrice');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1465','0','61567','0','Vizir Jin’bak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1412','0','56637','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1447','0','61485','0','General pa\'valak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1464','0','62205','0','Chef d\'escadre ner\'onok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1414','0','59479','469','last boss reward - heroic');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1413','0','56717','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1414','0','59479','465','last boss reward - normal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1417','0','56843','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1439','0','56439','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1416','0','56732','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1418','0','56448','464','last boss reward - normal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1418','0','56448','468','last boss reward - heroic');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1397','0','56906','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1405','0','56589','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1406','0','56636','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1419','0','56877','631','last boss reward - normal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1419','0','56877','471','last boss reward - heroic');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','56541','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1303','0','56747','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1305','0','56719','0','');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1306','0','56884','466','last boss reward - normal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1306','0','56884','470','last boss reward - heroic');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1502','0','61634','630','last boss reward - heroic');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1522','0','59303','473','last boss reward - heroic');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1530','0','59080','2','last boss reward - normal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1443','0','61408','0','Adarogg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1444','0','61412','0','Dark Shaman Koranthal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1445','0','61463','0','Slagmaw');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1446','0','61528','4','Lava Guard Gordoth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1577','0','69465','0','Jin\'rokh the Breaker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1575','0','68476','0','Horridon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1570','0','69134','0','Kaz\'rajin');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1565','0','67977','0','Tortos');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1578','1','140353','0','Megaera');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1573','0','69712','0','Ji-Kun');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1572','0','68036','0','Durumu The Forgotten');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1574','0','69017','0','Primordius');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1576','0','69427','0','Dark Animus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1559','0','68078','0','Iron Qon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1560','0','68904','0','Suen');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1579','0','68397','633','Lei Shen');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1580','0','69473','634','Ra-den');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1581','0','69473','634','Ra-den');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1602','0','71543','0','Immerseus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1598','0','71475','0','Fallen Protectors');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1624','0','72276','0','Norushen');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1604','0','71475','0','Sha of Pride');
