/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.6.17 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `content_loc9`, `content_loc10`) values('300000','The language filter has been disabled. You\'ll now see all messages in the World channel.',NULL,'Le filtre de langue a été désactivé. Désormais, vous verrez tous les messages du canal World, quelle que soit leur langue.','Der Sprachfilter wurde deaktiviert. Sie sehen nun alle Nachrichten im Worldchat.',NULL,NULL,'El filtro de idioma ha sido desactivado. Ahora verá todos los mensajes en el chat de World.','El filtro de idioma ha sido desactivado. Ahora verá todos los mensajes en el chat de World.','Фильтр языка отключен. Теперь вы видите сообщения на всех языках в общем канале общения.',NULL,'Il filtro della lingua è stato disabilitato. Adesso vedrai tutti i messaggi nel canale world.');
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `content_loc9`, `content_loc10`) values('300001','The language filter has been activated. You\'ll now only see messages from your language in the World channel.',NULL,'Le filtre de langue a été activé. Désormais, vous ne verrez plus que les messages du canal World dans votre langue.','Der Sprachfilter wurde aktiviert. Sie werden jetzt nur noch Nachrichten von Ihrer Sprache im Worldchat sehen.',NULL,NULL,'El filtro de idioma ha sido activado. Ahora solo verá mensajes de su idioma en el chat de World.','El filtro de idioma ha sido activado. Ahora solo verá mensajes de su idioma en el chat de World.','Фильтр языка активирован. Теперь вы видите только сообщения на вашем языке в общем канале общения.',NULL,'Il filtro della lingua è stato abilitato. Adesso vedrai solo i messaggi nella tua lingua nel canale world.');
