DELETE FROM `conditions` WHERE SourceEntry = 56169;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '77671',
        '0',
        '1',
        '29',
        '1',
        '41955',
        '40',
        '0',
        '0',
        '0',
        '',
        'Breathstone only usable on Imprisoned Warrior'),
	('17',
        '0',
        '77671',
        '0',
        '2',
        '29',
        '1',
        '41548',
        '40',
        '0',
        '0',
        '0',
        '',
        'Breathstone only usable on Imprisoned Soldier');