DELETE FROM `conditions` WHERE SourceEntry = 171772;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '171772',
        '0',
        '1',
        '29',
        '1',
        '80420',
        '40',
        '0',
        '0',
        '0',
        '',
        'Blixthraz Cannon only usable on some Clefthoof'),
        ('17',
        '0',
        '171772',
        '0',
        '2',
        '29',
        '1',
        '80136',
        '40',
        '0',
        '0',
        '0',
        '',
        'Blixthraz Cannon only usable on some Clefthoof'),
	('17',
        '0',
        '171772',
        '0',
        '3',
        '29',
        '1',
        '86847',
        '40',
        '0',
        '0',
        '0',
        '',
        'Blixthraz Cannon only usable on some Clefthoof'),
        ('17',
        '0',
        '171772',
        '0',
        '4',
        '29',
        '1',
        '78919',
        '40',
        '0',
        '0',
        '0',
        '',
        'Blixthraz Cannon only usable on some Clefthoof'),
	('17',
        '0',
        '171772',
        '0',
        '5',
        '29',
        '1',
        '86000',
        '40',
        '0',
        '0',
        '0',
        '',
        'Blixthraz Cannon only usable on some Clefthoof');