DELETE FROM `conditions` WHERE SourceEntry = 82799;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '82799',
        '0',
        '1',
        '29',
        '0',
        '44176',
        '15',
        '0',
        '0',
        '0',
        '',
        'Marked for Retrieval only usable on Murloc'),
        ('17',
        '0',
        '82799',
        '0',
        '2',
        '29',
        '0',
        '45401',
        '15',
        '0',
        '0',
        '0',
        '',
        'Marked for Retrieval only usable on Murloc'),
        ('17',
        '0',
        '82799',
        '0',
        '2',
        '29',
        '0',
        '44292',
        '15',
        '0',
        '0',
        '0',
        '',
        'Marked for Retrieval only usable on Murloc');