CREATE TABLE IF NOT EXISTS spell_stolen (spell_id INT(11), COMMENT BLOB NULL);
DELETE FROM spell_stolen WHERE spell_id = 175621;
INSERT INTO spell_stolen VALUE (175621, "Blackrock Foundry->Iron Flame Binder");
DELETE FROM spell_stolen WHERE spell_id = 161630;
INSERT INTO spell_stolen VALUE (161630, "Highmaul->Bladespire Sorcerer");
DELETE FROM spell_stolen WHERE spell_id = 161634;
INSERT INTO spell_stolen VALUE (161634, "Highmaul->Bladespire Sorcerer");
DELETE FROM spell_stolen WHERE spell_id = 175610;
INSERT INTO spell_stolen VALUE (175610, "Highmaul->Night-Twisted Shadowsworn");
DELETE FROM spell_stolen WHERE spell_id = 175899;
INSERT INTO spell_stolen VALUE (175899, "Highmaul->Gorian Runemaster");
DELETE FROM spell_stolen WHERE spell_id = 172066;
INSERT INTO spell_stolen VALUE (172066, "Highmaul->Oro");
DELETE FROM spell_stolen WHERE spell_id = 160312;
INSERT INTO spell_stolen VALUE (160312, "Auchindoun->Sargerei Cleric");
DELETE FROM spell_stolen WHERE spell_id = 157797;
INSERT INTO spell_stolen VALUE (157797, "Auchindoun->Sargerei Arbiter");
DELETE FROM spell_stolen WHERE spell_id = 176511;
INSERT INTO spell_stolen VALUE (176511, "Auchindoun->Sargerei Defender");
DELETE FROM spell_stolen WHERE spell_id = 172066;
INSERT INTO spell_stolen VALUE (157931, "Auchindoun->Sargerei Magus");
DELETE FROM spell_stolen WHERE spell_id = 176518;
INSERT INTO spell_stolen VALUE (176518, "Auchindoun->Sargerei Soulpriest");
DELETE FROM spell_stolen WHERE spell_id = 154415;
INSERT INTO spell_stolen VALUE (154415, "Auchindoun->Soulbinder Nyami");
DELETE FROM spell_stolen WHERE spell_id = 154477;
INSERT INTO spell_stolen VALUE (154477, "Auchindoun->Soulbinder Nyami");
DELETE FROM spell_stolen WHERE spell_id = 167092;
INSERT INTO spell_stolen VALUE (167092, "Auchindoun->Cackling Pyromaniac");
DELETE FROM spell_stolen WHERE spell_id = 178837;
INSERT INTO spell_stolen VALUE (178837, "Auchindoun->Cackling Pyromaniac");
DELETE FROM spell_stolen WHERE spell_id = 157053;
INSERT INTO spell_stolen VALUE (157053, "Auchindoun->Durag the Dominator");
DELETE FROM spell_stolen WHERE spell_id = 172054;
INSERT INTO spell_stolen VALUE (156854, "Auchindoun->Gul'kosh");
DELETE FROM spell_stolen WHERE spell_id = 156829;
INSERT INTO spell_stolen VALUE (156829, "Auchindoun->Gul'kosh");
DELETE FROM spell_stolen WHERE spell_id = 156954;
INSERT INTO spell_stolen VALUE (156954, "Auchindoun->Gul'kosh");
DELETE FROM spell_stolen WHERE spell_id = 157051;
INSERT INTO spell_stolen VALUE (157051, "Auchindoun->Grom'tash the Destructor");
DELETE FROM spell_stolen WHERE spell_id = 157049;
INSERT INTO spell_stolen VALUE (157049, "Auchindoun->Grom'tash the Destructor");
DELETE FROM spell_stolen WHERE spell_id = 156829;
INSERT INTO spell_stolen VALUE (156829, "Auchindoun->Teron'gor");
DELETE FROM spell_stolen WHERE spell_id = 156842;
INSERT INTO spell_stolen VALUE (156842, "Auchindoun->Teron'gor");
DELETE FROM spell_stolen WHERE spell_id = 156854;
INSERT INTO spell_stolen VALUE (156854, "Auchindoun->Teron'gor");
DELETE FROM spell_stolen WHERE spell_id = 156965;
INSERT INTO spell_stolen VALUE (156965, "Auchindoun->Teron'gor");
DELETE FROM spell_stolen WHERE spell_id = 151558;
INSERT INTO spell_stolen VALUE (151558, "Bloodmaul Slag Mines->Bloodmaul Ogre Mage");
DELETE FROM spell_stolen WHERE spell_id = 152427;
INSERT INTO spell_stolen VALUE (152427, "Bloodmaul Slag Mines->Magma Lord");
DELETE FROM spell_stolen WHERE spell_id = 150290;
INSERT INTO spell_stolen VALUE (150290, "Bloodmaul Slag Mines->Calamity");
DELETE FROM spell_stolen WHERE spell_id = 164615;
INSERT INTO spell_stolen VALUE (164615, "Bloodmaul Slag Mines->Bloodmaul Flamespeaker");
DELETE FROM spell_stolen WHERE spell_id = 15067;
INSERT INTO spell_stolen VALUE (15067, "Bloodmaul Slag Mines->Gug'rokk");
DELETE FROM spell_stolen WHERE spell_id = 165122;
INSERT INTO spell_stolen VALUE (165122, "Iron Docks->Ahro'ok Dugru");
DELETE FROM spell_stolen WHERE spell_id = 152814;
INSERT INTO spell_stolen VALUE (152814, "Shadowmoon Burial Grounds->Shadowmoon Bone-Mender");
DELETE FROM spell_stolen WHERE spell_id = 152819;
INSERT INTO spell_stolen VALUE (152819, "Shadowmoon Burial Grounds->Shadowmoon Bone-Mender");
DELETE FROM spell_stolen WHERE spell_id = 156776;
INSERT INTO spell_stolen VALUE (156776, "Shadowmoon Burial Grounds->Shadowmoon Enslaver");
DELETE FROM spell_stolen WHERE spell_id = 156722;
INSERT INTO spell_stolen VALUE (156722, "Shadowmoon Burial Grounds->Shadowmoon Exhumer");
DELETE FROM spell_stolen WHERE spell_id = 156717;
INSERT INTO spell_stolen VALUE (156717, "Shadowmoon Burial Grounds->Monstrous Corpse Spider");
DELETE FROM spell_stolen WHERE spell_id = 153524;
INSERT INTO spell_stolen VALUE (153524, "Shadowmoon Burial Grounds->Plagued Bat");
DELETE FROM spell_stolen WHERE spell_id = 152894;
INSERT INTO spell_stolen VALUE (152894, "Skyreach->Adept of the Dawn");
DELETE FROM spell_stolen WHERE spell_id = 154396;
INSERT INTO spell_stolen VALUE (154396, "Skyreach->High Sage Viryx");
DELETE FROM spell_stolen WHERE spell_id = 81985;
INSERT INTO spell_stolen VALUE (81985, "The Everbloom->Everbloom Tender");
DELETE FROM spell_stolen WHERE spell_id = 164973;
INSERT INTO spell_stolen VALUE (164973, "The Everbloom->Everbloom Tender");
DELETE FROM spell_stolen WHERE spell_id = 164973;
INSERT INTO spell_stolen VALUE (164973, "The Everbloom->Earthshaper Telu");
DELETE FROM spell_stolen WHERE spell_id = 169843;
INSERT INTO spell_stolen VALUE (169843, "The Everbloom->Putrid Pyromancer");
DELETE FROM spell_stolen WHERE spell_id = 155588;
INSERT INTO spell_stolen VALUE (155588, "Upper Blackrock Spire->Black Iron Dreadweaver");
DELETE FROM spell_stolen WHERE spell_id = 155587;
INSERT INTO spell_stolen VALUE (155587, "Upper Blackrock Spire->Black Iron Dreadweaver");
DELETE FROM spell_stolen WHERE spell_id = 155590;
INSERT INTO spell_stolen VALUE (155590, "Upper Blackrock Spire->Black Iron Summoner");
DELETE FROM spell_stolen WHERE spell_id = 155589;
INSERT INTO spell_stolen VALUE (155589, "Upper Blackrock Spire->Black Iron Summoner");
DELETE FROM spell_stolen WHERE spell_id = 163057;
INSERT INTO spell_stolen VALUE (163057, "Upper Blackrock Spire->Black Iron Flame Reaver");