DELETE FROM `conditions` WHERE SourceEntry = 87296;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '87296',
        '0',
        '2',
        '29',
        '0',
        '46166',
        '5',
        '0',
        '0',
        '0',
        '',
        'Marked for Retrieval only usable on Stonard Warrior');