-- Quest 34639 - Bonus Objective: Aruuna's Desolation
DELETE FROM `npc_spellclick_spells` WHERE npc_entry=79432;
INSERT INTO `npc_spellclick_spells` (npc_entry, spell_id, cast_flags, user_type) VALUES(79432, 160430, 1, 0);

UPDATE `creature_template` SET npcflag= `npcflag` | 0x01000000 WHERE entry= 79432;
UPDATE `creature` SET spawndist=10, `MovementType`=1 WHERE id=79432;

DELETE FROM `smart_scripts` WHERE `entryorguid` = 79432 AND `source_type` = 0;
INSERT INTO `smart_scripts` (
  `entryorguid`,
  `source_type`,
  `id`,
  `link`,
  `event_type`,
  `event_phase_mask`,
  `event_chance`,
  `event_flags`,
  `event_param1`,
  `event_param2`,
  `event_param3`,
  `event_param4`,
  `action_type`,
  `action_param1`,
  `action_param2`,
  `action_param3`,
  `action_param4`,
  `action_param5`,
  `action_param6`,
  `target_type`,
  `target_param1`,
  `target_param2`,
  `target_param3`,
  `target_x`,
  `target_y`,
  `target_z`,
  `target_o`,
  `comment`
) 
VALUES
  (
    '79432',
    '0',
    '0',
    '0',
    '23',
    '0',
    '100',
    '0',
    '160469',
    '0',
    '1',
    '1',
    '67',
    '1',
    '20000',
    '30000',
    '0',
    '0',
    '100',
    '1',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    'On debuff'
  ),
  (
    '79432',
    '0',
    '1',
    '0',
    '59',
    '0',
    '100',
    '0',
    '1',
    '0',
    '0',
    '0',
    '11',
    '160469',
    '2',
    '0',
    '0',
    '0',
    '0',
    '1',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    'Apply debuf'
  )  ;

