REPLACE INTO disables (sourceType, entry, COMMENT) VALUES
(7, 313, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 314, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 315, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 316, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 317, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 318, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 319, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 320, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 321, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 322, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 323, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 324, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 325, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 326, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 327, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 328, "Garrison Mission Not Available (Highmaul Raid)"),
(7, 427, "Garrison Mission Not Available (Slagworks)"),
(7, 428, "Garrison Mission Not Available (Black Forge)"),
(7, 429, "Garrison Mission Not Available (Iron Assembly)"),
(7, 430, "Garrison Mission Not Available (Blackhand's Crucible)"),
(7, 446, "Garrison Mission Not Available (Slagworks)"),
(7, 447, "Garrison Mission Not Available (Black Forge)"),
(7, 448, "Garrison Mission Not Available (Iron Assembly)"),
(7, 449, "Garrison Mission Not Available (Blackhand's Crucible)"),
(7, 450, "Garrison Mission Not Available (Slagworks)"),
(7, 451, "Garrison Mission Not Available (Black Forge)"),
(7, 452, "Garrison Mission Not Available (Iron Assembly)"),
(7, 453, "Garrison Mission Not Available (Blackhand's Crucible)"),
(7, 454, "Garrison Mission Not Available (Slagworks)"),
(7, 455, "Garrison Mission Not Available (Black Forge)"),
(7, 456, "Garrison Mission Not Available (Iron Assembly)"),
(7, 457, "Garrison Mission Not Available (Blackhand's Crucible)");