DELETE FROM `conditions` WHERE SourceEntry = 84009;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '84009',
        '0',
        '1',
        '29',
        '0',
        '44944',
        '15',
        '0',
        '0',
        '0',
        '',
        'Release Ebon Gargoyle only usable on Provincial Minuteman'),
        ('17',
        '0',
        '84009',
        '0',
        '2',
        '23',
        '0',
        '193',
        '0',
        '0',
        '0',
        '0',
        '',
        'Release Ebon Gargoyle only usable on Provincial Minuteman');