DELETE FROM `conditions` WHERE SourceEntry = 57853;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '57853',
        '0',
        '1',
        '29',
        '0',
        '30742',
        '5',
        '0',
        '0',
        '0',
        '',
        'Master Summoners Staff only usable on Summoning Altar'),
        ('17',
        '0',
        '57853',
        '0',
        '2',
        '29',
        '0',
        '30744',
        '5',
        '0',
        '0',
        '0',
        '',
        'Master Summoners Staff only usable on Summoning Altar'),
         ('17',
        '0',
        '57853',
        '0',
        '3',
        '29',
        '0',
        '30745',
        '5',
        '0',
        '0',
        '0',
        '',
        'Master Summoners Staff only usable on Summoning Altar'),
         ('17',
        '0',
        '57853',
        '0',
        '4',
        '29',
        '0',
        '30950',
        '5',
        '0',
        '0',
        '0',
        '',
        'Master Summoners Staff only usable on Summoning Altar');