DELETE FROM `conditions` WHERE SourceEntry = 48345;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '48345',
        '0',
        '0',
        '22',
        '0',
        '571',
        '0',
        '0',
        '0',
        '0',
        '',
        'Siegesmith Bombs only usable on Norfendre');