DELETE FROM `conditions` WHERE SourceEntry = 85252;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '85252',
        '0',
        '2',
        '29',
        '0',
        '45695',
        '5',
        '0',
        '0',
        '0',
        '',
        'Light-Touched Blades only usable on Slain Scourge Trooper');