DELETE FROM `conditions` WHERE SourceEntry = 45030;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '45030',
        '0',
        '1',
        '29',
        '0',
        '25001',
        '5',
        '0',
        '0',
        '0',
        '',
        'Impale Emissary only usable on Burning Legion Demon'),
        ('17',
        '0',
        '45030',
        '0',
        '2',
        '29',
        '0',
        '25002',
        '5',
        '0',
        '0',
        '0',
        '',
        'Impale Emissary only usable on Burning Legion Demon'),
        ('17',
        '0',
        '45030',
        '0',
        '3',
        '29',
        '0',
        '24999',
        '5',
        '0',
        '0',
        '0',
        '',
        'Impale Emissary only usable on Burning Legion Demon'),
        ('17',
        '0',
        '45030',
        '0',
        '4',
        '29',
        '0',
        '25068',
        '5',
        '0',
        '0',
        '0',
        '',
        'Impale Emissary only usable on Burning Legion Demon');