DELETE FROM `conditions` WHERE SourceEntry = 123803;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '123803',
        '0',
        '0',
        '29',
        '1',
        '63376',
        '30',
        '0',
        '0',
        '0',
        '',
        'Bag of Clams only usable on Coldwhisker Otter');