REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74790, 0, 0, "Je vais me faire un plaisir de vous briser.", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74790, 0, 1, "Dabord, je vais briser votre esprit. Ensuite je vendrai votre avenir.", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74790, 0, 2, "Brûlez !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74790, 0, 3, "Les éléments mécoutent et mobéissent !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74790, 0, 4, "|TInterface\Icons\spell_fire_elementaldevastation.blp:20|t |cFFF00000|Hspell:150678|h[Cœur de la fournaise]|h|r permet à %s de libérer un |cFFF00000|Hspell:150682|h[Barrage de lave]|h|r !", 41, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74790, 0, 5, "Vous serez les esclaves de la mine !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74790, 0, 6, "Vous ne serez… jamais… libres…", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75814, 0, 0, "Le feu ça brûle !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75814, 0, 1, "Argh ! Ça brûle !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75814, 0, 2, "Ouille, ouille, ouille !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75814, 0, 3, "À laide ! Je tombe !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75211, 0, 0, "Le monde brûlera !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(83623, 0, 0, "HAAAAAAAAAAAA ! TOUT CE FEU !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74366, 0, 0, "Partez ! Je me charge de réparer ça.", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74366, 0, 1, "Heu… pierre !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74366, 0, 2, "Les rochers sont stupides.", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74366, 0, 3, "Des flammes !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74366, 0, 4, "Ha ha ha ! Si faible.", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74366, 0, 5, "Aïe ! Noooon…", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 0, "Oui… la brute saffaiblit…", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 1, "Tuez-le ! Que je sois libéré !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 2, "Vous nêtes quun gravillon parmi les rochers…", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 3, "Je suis un éboulement !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 4, "Je mettrai fin à votre existence.", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 5, "Soyez réduits en poussière…", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 6, "%s invoque un |cFFFF0404|Hspell:150045|h[Impact de lave]|h|r !", 41, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 7, "Je vais vous réduire en cendres !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 8, "Détruire !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 9, "Serviteurs, à moi !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(74475, 0, 10, "Je reviens à la terre…", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75426, 0, 0, "Vous savez où vont les esclaves qui senfuient.", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75427, 0, 0, "Pitié, non ! Je nessayerai plus de méchapper !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75427, 0, 1, "Nooooooooooooooooooooooooooon !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75196, 0, 0, "Pour séchapper, cest maintenant ou jamais !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75195, 0, 0, "Pour séchapper, cest maintenant ou jamais !", 14, 0, 100);
REPLACE INTO creature_text (entry, `groupid`, `id`, `text`, `type`, `language`, `probability`) VALUES(75406, 0, 0, "|cFFF00000Scoria|r surgit de la lave !", 41, 0, 100);