SET @NPC_ID = 900014;
SET @NPC_DISPLAY_ID = 28324;
SET @NPC_NAME = "Legendary Transmogrificator";
SET @NPC_SUBNAME = "";
SET @NPC_SCRIPT = "npc_legendary_transmogrificator";
SET @SLOT = 1;
SET @EXTENTED_COST = 5213;

DELETE FROM `creature_template` where `entry` = @NPC_ID;
INSERT INTO `creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `femaleName`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_req`, `faction`, `npcflag`, `npcflag2`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `rank`, `dmgschool`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `baseVariance`, `rangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `WorldEffectID`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `TrackingQuestID`, `VignetteID`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `BuildVerified`)
 VALUES (@NPC_ID, '0', '0', @NPC_DISPLAY_ID, '0', '0', '0', @NPC_NAME, '', @NPC_SUBNAME, '', '0', '100', '100', '0', '0', '35', '1', '0', '2.8', '2.14286', '1.14286', '1', '0', '0', '35', '1200', '2000', '1', '1', '1', '64', '2048', '0', '0', '0', '0', '0', '0', '0', '0', '7', '76', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '100', '100', '', '0', '3', '1', '112.5', '150', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', @NPC_SCRIPT, '20779'); 

DELETE FROM `npc_vendor` where `entry` = @NPC_ID;

DELETE FROM trinity_string WHERE entry BETWEEN 30000 AND 30028;

insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30000,'Transmogrifications removed from equipped items',NULL,'Supprimer la transmogrification de l\'équipement',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30001,'You have no transmogrified items equipped',NULL,'Vous n\'avez aucun objet transmogrifié',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30002,'%s transmogrification removed',NULL,'%s transmogrification supprimé',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30003,'No transmogrification on %s slot',NULL,'Aucune transmogrification sur %s emplacement',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30004,'%s transmogrified',NULL,'%s transmogrifié',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30005,'Selected items are not suitable',NULL,'Les objets selectionnés ',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30006,'Selected item does not exist',NULL,'L\'object séléctionné n\'éxiste pas',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30007,'Equipment slot is empty',NULL,'Le slot d\'équipement est vide',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30008,'Head',NULL,'Tête',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30009,'Shoulders',NULL,'Epaules',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30010,'Shirt',NULL,'Chemise',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30011,'Chest',NULL,'Torse',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30012,'Waist',NULL,'Taille',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30013,'Legs',NULL,'Jambes',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30014,'Feet',NULL,'Pieds',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30015,'Wrists',NULL,'Poignets',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30016,'Hands',NULL,'Mains',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30017,'Back',NULL,'Dos',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30018,'Main hand',NULL,'Main droite',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30019,'Off hand',NULL,'Main gauche',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30020,'Ranged',NULL,'Arme à distance',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30021,'Tabard',NULL,'Tabard',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30022,'Back..',NULL,'Retour..',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30023,'Remove all transmogrifications',NULL,'Supprimer toutes les transmogrifications',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30024,'Remove transmogrifications from all equipped items',NULL,'Supprimés toutes les transmogrifications de tout les objets équipés?',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30025,'Update menu',NULL,'Mettre à jour le menu',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30026,'Remove transmogrification',NULL,'Supprimer la Transmogrification ',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30027,'Remove transmogrification from %s',NULL,'Supprimer la transmogrification de %s?',NULL,NULL,NULL,NULL,NULL,NULL);
insert into `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) values(30028,'Using this item for transmogrify will bind it to you and make it non-refundable and non-tradeable.rnDo you wish to continuernrn',NULL,'Si vous transmogrifié cet objet il sera lié, non-échangeable et non-remboursable \r\n Voulez vous continuer ?\r\n\r\n',NULL,NULL,NULL,NULL,NULL,NULL);
