DELETE FROM spell_script_names WHERE ScriptName = 'spell_mage_incanters_flow';
INSERT INTO spell_script_names VALUES (1463, 'spell_mage_incanters_flow');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_pal_enhanced_holy_shock';
INSERT INTO spell_script_names VALUES (157478, 'spell_pal_enhanced_holy_shock');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_pri_words_of_mending';
INSERT INTO spell_script_names VALUES (152117, 'spell_pri_words_of_mending');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_rog_death_from_above_return';
INSERT INTO spell_script_names VALUES (178236, 'spell_rog_death_from_above_return');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_rog_death_from_above';
INSERT INTO spell_script_names VALUES (152150, 'spell_rog_death_from_above');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_warr_sweeping_strikes';
INSERT INTO spell_script_names VALUES (12723, 'spell_warr_sweeping_strikes');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_monk_uplift';
INSERT INTO spell_script_names VALUES (116670, 'spell_monk_uplift');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_monk_stance_of_tiger';
INSERT INTO spell_script_names VALUES (103985, 'spell_monk_stance_of_tiger');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_monk_legacy_of_the_emperor';
INSERT INTO spell_script_names VALUES (115921, 'spell_monk_legacy_of_the_emperor');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_q31049_fae_spirit';
INSERT INTO spell_script_names VALUES (122567, 'spell_q31049_fae_spirit');
DELETE FROM spell_script_names WHERE ScriptName = 'spell_pri_item_s12_4p_heal';
INSERT INTO spell_script_names VALUES (26171, 'spell_pri_item_s12_4p_heal');
