-- Quest 34378 Establish Your Garrison
DELETE FROM quest_poi  WHERE QuestID=34378;
DELETE FROM quest_poi_points  WHERE questId=34378;
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34378, 0, 32, 1116, 941, 0, 0, 0, 0, 0, 859414) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34378, 0, 0, 5629, 4526) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34378, 1, 0, 1116, 981, 0, 0, 0, 0, 0, 920544) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34378, 1, 0, 5567, 4636) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34378, 2, 0, 1116, 990, 0, 0, 0, 0, 0, 920544) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34378, 2, 0, 5567, 4636) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);

-- Quest 34822 What We Need
DELETE FROM quest_poi  WHERE QuestID=34822;
DELETE FROM quest_poi_points  WHERE questId=34822;
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34822, 0, 32, 1116, 980, 0, 0, 0, 0, 0, 869027) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34822, 0, 0, 5564, 4517) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);

-- Quest 34823 The Ogron Live?
DELETE FROM quest_poi  WHERE QuestID=34823;
DELETE FROM quest_poi_points  WHERE questId=34823;
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34823, 0, 0, 1116, 941, 0, 0, 0, 0, 26057, 875433) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34823, 0, 0, 5862, 4943) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34823, 1, 0, 1116, 941, 0, 0, 0, 0, 26056, 950544) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34823, 1, 0, 5802, 5043) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34823, 2, -1, 1116, 990, 0, 0, 0, 0, 30954, 894330) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34823, 2, 0, 5614, 4563) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34823, 3, -1, 1116, 941, 0, 0, 0, 0, 30903, 0) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34823, 3, 0, 5579, 4586) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);

-- Quest 34824 What We Got
DELETE FROM quest_poi  WHERE QuestID=34824;
DELETE FROM quest_poi_points  WHERE questId=34824;
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 0, 32, 1116, 980, 0, 0, 0, 0, 0, 869027) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 0, 0, 5564, 4517) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 1, 32, 1116, 981, 0, 0, 0, 0, 0, 931570) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 1, 0, 5579, 4621) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 2, 32, 1116, 990, 0, 0, 0, 0, 0, 894326) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 2, 0, 5554, 4589) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 3, 0, 1116, 980, 0, 0, 0, 0, 30952, 954309) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 3, 0, 5566, 4499) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 4, 0, 1116, 981, 0, 0, 0, 0, 30954, 954314) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 4, 0, 5592, 4591) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 5, 0, 1116, 981, 0, 0, 0, 0, 30954, 954314) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 5, 0, 5592, 4591) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 6, 0, 1116, 981, 0, 0, 0, 0, 30954, 954314) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 6, 0, 5592, 4591) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 7, 0, 1116, 981, 0, 0, 0, 0, 30954, 954314) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 7, 0, 5592, 4591) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 8, 0, 1116, 990, 0, 0, 0, 0, 30953, 954312) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 8, 0, 5589, 4597) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 9, 0, 1116, 990, 0, 0, 0, 0, 30953, 954312) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 9, 0, 5589, 4597) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 10, 0, 1116, 990, 0, 0, 0, 0, 30953, 954312) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 10, 0, 5589, 4597) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34824, 11, 0, 1116, 990, 0, 0, 0, 0, 30953, 954312) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34824, 11, 0, 5589, 4597) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);

-- Quest 34461 Build Your Barracks
DELETE FROM quest_poi  WHERE QuestID=34461;
DELETE FROM quest_poi_points  WHERE questId=34461;
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 0, 32, 1116, 980, 0, 0, 0, 0, 30952, 869027) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 0, 0, 5564, 4517) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 1, 32, 1116, 981, 0, 0, 0, 0, 30954, 931570) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 1, 0, 5579, 4621) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 2, 32, 1116, 990, 0, 0, 0, 0, 30953, 894326) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 2, 0, 5554, 4589) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 3, 0, 1116, 980, 0, 0, 0, 0, 30952, 878010) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 3, 0, 5579, 4465) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 4, 0, 1116, 981, 0, 0, 0, 0, 30954, 940281) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 4, 0, 5579, 4465) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 5, 0, 1116, 981, 0, 0, 0, 0, 30954, 940281) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 5, 0, 5579, 4465) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 6, 0, 1116, 981, 0, 0, 0, 0, 30954, 940281) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 6, 0, 5579, 4465) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 7, 0, 1116, 981, 0, 0, 0, 0, 30954, 940281) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 7, 0, 5579, 4465) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 8, 0, 1116, 990, 0, 0, 0, 0, 30953, 894393) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 8, 0, 5572, 4456) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 9, 0, 1116, 990, 0, 0, 0, 0, 30953, 894393) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 9, 0, 5572, 4456) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 10, 0, 1116, 990, 0, 0, 0, 0, 30953, 894393) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 10, 0, 5572, 4456) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34461, 11, 0, 1116, 990, 0, 0, 0, 0, 30953, 894393) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34461, 11, 0, 5572, 4456) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);

-- Quest 34861 We Need An Army
DELETE FROM quest_poi  WHERE QuestID=34861;
DELETE FROM quest_poi_points  WHERE questId=34861;
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34861, 0, 32, 1116, 980, 0, 0, 0, 0, 0, 869027) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34861, 0, 0, 5564, 4517) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34861, 1, 32, 1116, 981, 0, 0, 0, 0, 0, 931570) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34861, 1, 0, 5579, 4621) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34861, 2, 32, 1116, 990, 0, 0, 0, 0, 0, 894326) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34861, 2, 0, 5554, 4589) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);

-- Quest 34462 Winds of Change
DELETE FROM quest_poi  WHERE QuestID=34462;
DELETE FROM quest_poi_points  WHERE questId=34462;
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34462, 0, 0, 1116, 941, 0, 0, 0, 0, 0, 0) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34462, 0, 0, 5710, 4001) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34462, 1, -1, 1116, 941, 0, 0, 0, 0, 30903, 877089) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34462, 1, 0, 5646, 4542) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34462, 2, -1, 1116, 981, 0, 0, 0, 0, 30954, 931569) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34462, 2, 0, 5555, 4610) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);
INSERT INTO quest_poi (`QuestID`, `BlobIndex`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `WorldEffectID`, `PlayerConditionID`, `Unk`) VALUES(34462, 3, -1, 1116, 990, 0, 0, 0, 0, 30953, 894327) ON DUPLICATE KEY UPDATE `QuestID` = VALUES(`QuestID`), `BlobIndex` = VALUES(`BlobIndex`), `ObjectiveIndex` = VALUES(`ObjectiveIndex`), `MapID` = VALUES(`MapID`), `WorldMapAreaId` = VALUES(`WorldMapAreaId`), `Floor` = VALUES(`Floor`), `Priority` = VALUES(`Priority`), `Flags` = VALUES(`Flags`), `WorldEffectID` = VALUES(`WorldEffectID`), `PlayerConditionID` = VALUES(`PlayerConditionID`), `Unk` = VALUES(`Unk`);
INSERT INTO quest_poi_points (`questId`, `id`, `idx`, `x`, `y`) VALUES(34462, 3, 0, 5558, 4602) ON DUPLICATE KEY UPDATE `questId` = VALUES(`questId`), `id` = VALUES(`id`), `idx` = VALUES(`idx`), `x` = VALUES(`x`), `y` = VALUES(`y`);