drop table if exists instance_encounters;
create table `instance_encounters` (
	`entry` int (10),
	`creditType` tinyint (3),
	`creditEntry` int (10),
	`lastEncounterDungeon` smallint (5),
	`comment` varchar (2295)
); 

alter table `world_test`.`instance_encounters` 
   change `creditEntry` `creditEntry` int(10) NOT NULL,
   drop primary key, 
   add primary key(`creditEntry`);
   
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('463','0','1853',NULL,'Darkmaster Gandling');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('554','0','2748',NULL,'Archaedas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('587','0','3653',NULL,'Kresh');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('592','0','3654',NULL,'Mutanus the Devourer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('586','0','3669',NULL,'Lord Cobrahn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('588','0','3670',NULL,'Lord Pythas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('585','0','3671',NULL,'Lady Anacondra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('590','0','3673',NULL,'Lord Serpentis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('589','0','3674',NULL,'Skum');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('446','0','3974',NULL,'Houndmaster Loksey');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('448','0','3975',NULL,'Herod');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('450','0','3977',NULL,'High Inquisitor Whitemane');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('444','0','3983',NULL,'Interrogator Vishas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('449','0','4542',NULL,'High Inquisitor Fairbanks');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('553','0','4854',NULL,'Grimlok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('493','0','5709',NULL,'Shade of Eranikus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('488','0','5710',NULL,'Jammal\'an the Prophet');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('490','0','5719',NULL,'Morphaz');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('487','0','5720',NULL,'Weaver');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('486','0','5721',NULL,'Dreamscythe');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('491','0','5722',NULL,'Hazzas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('591','0','5775',NULL,'Verdan the Everliving');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('438','0','6168',NULL,'Roogug');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('381','0','6229',NULL,'Crowd Pummeler 9-60');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('380','0','6235',NULL,'Electrocutioner 6000');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('447','0','6487',NULL,'Arcanist Doan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('547','0','6910',NULL,'Revelosh');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('378','0','7079',NULL,'Viscous Fallout');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('551','0','7206',NULL,'Ancient Stone Keeper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('549','0','7228',NULL,'Ironaya');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('600','0','7267',NULL,'Chief Ukorz Sandscalp');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('597','0','7271',NULL,'Witch Doctor Zum\'rah');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('596','0','7272',NULL,'Theka the Martyr');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('599','0','7275',NULL,'Shadowpriest Sezz\'ziz');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('552','0','7291',NULL,'Galgann Firehammer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1663','0','7357',NULL,'Mordresh Fire Eye');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1666','0','7358',NULL,'Amnennar the Coldbringer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('379','0','7361',NULL,'Grubbis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('593','0','7795',NULL,'Hydromancer Velratha');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('598','0','7796',NULL,'Nekrum Gutchewer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('382','0','7800',NULL,'Mekgineer Thermaplugg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('595','0','8127',NULL,'Antu\'sul');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('492','0','8443',NULL,'Avatar of Hakkar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('237','0','8983',NULL,'Golem Lord Argelmach');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('235','0','9016',NULL,'Bael\'Gar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('232','0','9017',NULL,'Lord Incendius');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('227','0','9018',NULL,'High Interrogator Gerstahn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('245','0','9019',NULL,'Emperor Dagran Thaurissan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('231','0','9024',NULL,'Pyromancer Loregrain');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('228','0','9025',NULL,'Lord Roccor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('236','0','9033',NULL,'General Angerforge');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('233','0','9041',NULL,'Warder Stilgiss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('234','0','9056',NULL,'Fineous Darkvire');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('242','0','9156',NULL,'Ambassador Flamelash');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('267','0','9196',NULL,'Highlord Omokk');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('268','0','9236',NULL,'Shadow Hunter Vosh\'gajin');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('269','0','9237',NULL,'War Master Voone');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('229','0','9319',NULL,'Houndmaster Grebmar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('241','0','9499',NULL,'Plugger Spazzring');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('239','0','9502',NULL,'Phalanx');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('238','0','9537',NULL,'Hurley Blackbreath');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('240','0','9543',NULL,'Ribbly Screwspigot');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('275','0','9568',NULL,'Overlord Wyrmthalak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('272','0','9736',NULL,'Quartermaster Zigris');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('244','0','9938',NULL,'Magmus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('274','0','10220',NULL,'Halycon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('250','0','10237',NULL,'Yor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('273','0','10268',NULL,'Gizrul the Slavener');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('455','0','10432',NULL,'Vectus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('454','0','10433',NULL,'Marduk Blackpool');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('482','0','10435',NULL,'Magistrate Barthilas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('479','0','10436',NULL,'Baroness Anastari');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('480','0','10437',NULL,'Nerub\'enkan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('481','0','10438',NULL,'Maleki the Pallid');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('483','0','10439',NULL,'Ramstein the Gorger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('462','0','10502',NULL,'Lady Illucia Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('452','0','10503',NULL,'Jandice Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('461','0','10504',NULL,'Lord Alexei Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('457','0','10505',NULL,'Instructor Malicia');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('451','0','10506',NULL,'Kirtonos the Herald');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('460','0','10507',NULL,'The Ravenian');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('456','0','10508',NULL,'Ras Frostwhisper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('472','0','10516',NULL,'The Unforgiven');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('473','0','10558',NULL,'Hearthsinger Forresten');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('271','0','10584',NULL,'Urok Doomhowl');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('270','0','10596',NULL,'Mother Smolderweb');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('474','0','10808',NULL,'Timmy the Cruel');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('477','0','10811',NULL,'Instructor Galford');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('478','0','10813',NULL,'Balnazzar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('459','0','10901',NULL,'Lorekeeper Polkelt');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('475','0','10997',NULL,'Willey Hopebreaker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('476','0','11032',NULL,'Commander Malor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('458','0','11261',NULL,'Doctor Theolen Krastinov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('792','0','11380',NULL,'Jin\'do the Hexxer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','11382',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('361','0','11486',NULL,'Prince Tortheldrin');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('348','0','11487',NULL,'Magister Kalendris');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('347','0','11488',NULL,'Illyanna Ravenoak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('350','0','11489',NULL,'Tendris Warpwood');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('343','0','11490',NULL,'Zevrim Thornhoof');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('346','0','11492',NULL,'Alzzin the Wildshaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('349','0','11496',NULL,'Immol\'thar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('368','0','11501',NULL,'King Gordok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('453','0','11622',NULL,'Rattlegore');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('429','0','12201',NULL,'Princess Theradras');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('426','0','12203',NULL,'Landslide');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('425','0','12225',NULL,'Celebras the Cursed');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('424','0','12236',NULL,'Lord Vyletongue');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('423','0','12258',NULL,'Razorlash');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('344','0','13280',NULL,'Hydrospawn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('422','0','13282',NULL,'Noxxion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('428','0','13596',NULL,'Rotgrip');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('427','0','13601',NULL,'Tinkerer Gizlock');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('364','0','14321',NULL,'Guard Fengus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('363','0','14322',NULL,'Stomper Kreeg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('365','0','14323',NULL,'Guard Slip\'kik');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('367','0','14324',NULL,'Cho\'Rush the Observer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('366','0','14325',NULL,'Captain Kromcrush');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('362','0','14326',NULL,'Guard Mol\'dar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('345','0','14327',NULL,'Lethtendris');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('784','0','14507',NULL,'High Priest Venoxis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('789','0','14509',NULL,'High Priest Thekal');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('786','0','14510',NULL,'High Priestess Mar\'li');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('791','0','14515',NULL,'High Priestess Arlokk');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('785','0','14517',NULL,'High Priestess Jeklik');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('793','0','14834',NULL,'Hakkar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('790','0','15114',NULL,'Gahz\'ranka');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('408','0','16807',NULL,'Grand Warlock Nethekurse');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('413','0','16808',NULL,'Warchief Kargath Bladefist');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('411','0','16809',NULL,'Warbringer O\'mrogg');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('393','0','17306',NULL,'Watchkeeper Gargolmar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('397','0','17307',NULL,'Vazruden the Herald');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('395','0','17308',NULL,'Omor the Unscarred');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('406','0','17377',NULL,'Keli\'dan the Breaker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('404','0','17380',NULL,'Broggok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('402','0','17381',NULL,'The Maker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('321','0','17770',NULL,'Hungarfen');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('317','0','17796',NULL,'Mekgineer Steamrigger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('315','0','17797',NULL,'Hydromancer Thespia');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('319','0','17798',NULL,'Warlord Kalithresh');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('330','0','17826',NULL,'Swamplord Musel\'ek');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('285','0','17848',NULL,'Lieutenant Drake');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('284','0','17862',NULL,'Captain Skarloc');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('288','0','17879',NULL,'Chrono Lord Deja');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('290','0','17880',NULL,'Temporus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('292','0','17881',NULL,'Aeonus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('332','0','17882',NULL,'The Black Stalker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('304','0','17941',NULL,'Mennu the Betrayer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('306','0','17942',NULL,'Quagmirran');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('506','0','17975',NULL,'High Botanist Freywinn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('504','0','17976',NULL,'Commander Sarannis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('512','0','17977',NULL,'Warp Splinter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('508','0','17978',NULL,'Thorngrin the Tender');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('510','0','17980',NULL,'Laj');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('305','0','17991',NULL,'Rokmar the Crackler');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('282','0','18096',NULL,'Epoch Hunter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('323','0','18105',NULL,'Ghaz\'an');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('248','0','18341',NULL,'Pandemonius');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('249','0','18343',NULL,'Tavarok');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('251','0','18344',NULL,'Nexus-Prince Shaffar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('246','0','18371',NULL,'Shirrak the Dead Watcher');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','18373',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('252','0','18472',NULL,'Darkweaver Syth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('254','0','18473',NULL,'Talon King Ikiss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','18667',NULL,'Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('258','0','18708',NULL,'Murmur');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('255','0','18731',NULL,'Ambassador Hellmaw');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('257','0','18732',NULL,'Grandmaster Vorpil');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('514','0','19219',NULL,'Mechano-Lord Capacitus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('518','0','19220',NULL,'Pathaleon the Calculator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('516','0','19221',NULL,'Nethermancer Sepethrea');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','19300',NULL,'Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','19301',NULL,'Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','19302',NULL,'Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','19303',NULL,'Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','19304',NULL,'Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('421','0','19622',NULL,'Kael\'thas Sunstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('447','0','20352',NULL,'Arcanist Doan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('495','0','20870',NULL,'Zereketh the Unbound');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('497','0','20885',NULL,'Dalliah the Doomsayer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('499','0','20886',NULL,'Wrath-Scryer Soccothrates');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('501','0','20912',NULL,'Harbinger Skyriss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('409','0','20923',NULL,'Blood Guard Porung');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('501','0','21466',NULL,'Harbinger Skyriss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('501','0','21467',NULL,'Harbinger Skyriss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('250','0','22930',NULL,'Yor');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('253','0','23035',NULL,'Anzu');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('421','0','23054',NULL,'Kael\'thas Sunstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','23953',NULL,'Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('576','0','23954',NULL,'Ingvar the Plunderer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('576','0','23980',NULL,'Ingvar the Plunderer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','24041',NULL,'Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('584','0','24321',NULL,'King Ymiron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('419','0','24560',NULL,'Priestess Delrissa');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('421','0','24664',NULL,'Kael\'thas Sunstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('415','0','24723',NULL,'Selin Fireheart');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('417','0','24744',NULL,'Vexallus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('562','0','24847',NULL,'Loken');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('527','0','26206',NULL,'Keristrasza');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('527','0','26237',NULL,'Keristrasza');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('297','0','26529',NULL,'Meathook');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('299','0','26532',NULL,'Chrono-Lord Epoch');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('300','0','26533',NULL,'Mal\'Ganis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('370','0','26630',NULL,'Trollgore');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('372','0','26631',NULL,'Novos the Summoner');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('376','0','26632',NULL,'The Prophet Tharon\'ja');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('578','0','26668',NULL,'Svala Sorrowgrave');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('580','0','26687',NULL,'Gortok Palehoof');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('582','0','26693',NULL,'Skadi the Ruthless');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('527','0','26723',NULL,'Keristrasza');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('521','0','26731',NULL,'Grand Magus Telestra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('523','0','26763',NULL,'Anomalus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('525','0','26794',NULL,'Ormorok the Tree-Shaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('521','0','26832',NULL,'Grand Magus Telestra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('584','0','26861',NULL,'King Ymiron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('521','0','26928',NULL,'Grand Magus Telestra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('521','0','26929',NULL,'Grand Magus Telestra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('521','0','26930',NULL,'Grand Magus Telestra');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('531','0','27447',NULL,'Varos Cloudstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('374','0','27483',NULL,'King Dred');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','27618',NULL,'Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('529','0','27654',NULL,'Drakos the Interrogator');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('533','0','27655',NULL,'Mage-Lord Urom');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('535','0','27656',NULL,'Ley-Guardian Eregos');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('376','0','27696',NULL,'The Prophet Tharon\'ja');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('566','0','27975',NULL,'Maiden of Grief');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('564','0','27977',NULL,'Krystallus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('570','0','27978',NULL,'Sjonnir The Ironshaper');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','28356',NULL,'Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('560','0','28546',NULL,'Ionar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('556','0','28586',NULL,'General Bjarngrim');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('558','0','28587',NULL,'Volkhan');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('264','0','28684',NULL,'Krik\'thir the Gatewatcher');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','28911',NULL,'Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('265','0','28921',NULL,'Hadronox');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('562','0','28923',NULL,'Loken');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','29108',NULL,'Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('266','0','29120',NULL,'Anub\'arak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('384','0','29304',NULL,'Slad\'ran');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('388','0','29305',NULL,'Moorabi');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('391','0','29306',NULL,'Gal\'darah');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('386','0','29307',NULL,'Drakkari Colossus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('260','0','29308',NULL,'Prince Taldaram');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('259','0','29309',NULL,'Elder Nadox');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('261','0','29310',NULL,'Jedoga Shadowseeker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('263','0','29311',NULL,'Herald Volazj');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('584','0','29393',NULL,'King Ymiron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('389','0','29932',NULL,'Eck the Ferocious');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('339','0','30188',NULL,'Argent Champion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('262','0','30258',NULL,'Amanitar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('562','0','30396',NULL,'Loken');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1093','0','30449',NULL,'Vesperon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1091','0','30451',NULL,'Shadron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1092','0','30452',NULL,'Tenebron');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('473','0','30551',NULL,'Hearthsinger Forresten');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('339','0','30675',NULL,'Argent Champion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('482','0','30994',NULL,'Magistrate Barthilas');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('546','0','31134',NULL,'Cyanigosa');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('341','0','33546',NULL,'The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('339','0','33707',NULL,'Argent Champion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('341','0','33785',NULL,'The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('527','0','34310',NULL,'Keristrasza');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('266','0','34564',NULL,'Anub\'arak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('266','0','34660',NULL,'Anub\'arak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('341','0','35444',NULL,'The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('341','0','35451',NULL,'The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('341','0','35547',NULL,'The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('341','0','35557',NULL,'The Black Knight');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('836','0','36477',NULL,'Krick');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('834','0','36494',NULL,'Forgemaster Garfrost');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('830','0','36497',NULL,'Bronjahm');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('832','0','36502',NULL,'Devourer of Souls');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('832','0','36503',NULL,'Devourer of Souls');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('832','0','36504',NULL,'Devourer of Souls');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('838','0','36658',NULL,'Scourgelord Tyrannus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('838','0','36794',NULL,'Scourgelord Tyrannus');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('339','0','37928',NULL,'Argent Champion');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('572','0','37972',NULL,'Prince Keleseth');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('260','0','37973',NULL,'Prince Taldaram');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('841','0','38112',NULL,'Falric');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('839','0','38113',NULL,'Marwyn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','42790',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','42799',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','42842',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','42941',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('785','0','43257',NULL,'High Priestess Jeklik');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('784','0','43323',NULL,'High Priest Venoxis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','43989',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('460','0','44317',NULL,'The Ravenian');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('453','0','44318',NULL,'Rattlegore');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('463','0','44323',NULL,'Darkmaster Gandling');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('457','0','44442',NULL,'Instructor Malicia');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('451','0','44483',NULL,'Kirtonos the Herald');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('484','0','45412',NULL,'Lord Aurius Rivendare');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('479','0','45956',NULL,'Baroness Anastari');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('488','0','46656',NULL,'Jammal\'an the Prophet');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','52151',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('784','0','52155',NULL,'High Priest Venoxis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('784','0','52191',NULL,'High Priest Venoxis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('784','0','52301',NULL,'High Priest Venoxis');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('787','0','52411',NULL,'Bloodlord Mandokir');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','56541',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','56713',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1417','0','56786',NULL,'Lorewalker Stonestep');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1417','0','56843',NULL,'Lorewalker Stonestep');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','56870',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1419','0','56877',NULL,'Raigonn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1419','0','56897',NULL,'Raigonn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('463','0','58875',NULL,'Darkmaster Gandling');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('463','0','59080',NULL,'Darkmaster Gandling');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('453','0','59153',NULL,'Rattlegore');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('452','0','59184',NULL,'Jandice Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('452','0','59217',NULL,'Jandice Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('452','0','59220',NULL,'Jandice Barov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('458','0','59369',NULL,'Doctor Theolen Krastinov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','60005',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','60006',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','60007',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1564','0','60491',NULL,'Sha of Anger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1419','0','61177',NULL,'Raigonn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1564','0','61523',NULL,'Sha of Anger');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1563','0','62346',NULL,'Galleon');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','63009',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','64387',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('458','0','65631',NULL,'Doctor Theolen Krastinov');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','67229',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1572','0','67853',NULL,'Durumu the Forgotten');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1572','0','68036',NULL,'Durumu the Forgotten');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1578','0','68065',NULL,'Megaera');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1571','0','69099',NULL,'Nalak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('786','0','69132',NULL,'High Priestess Mar\'li');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1587','0','69161',NULL,'Oondasta');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1572','0','69392',NULL,'Durumu the Forgotten');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1571','0','69562',NULL,'Nalak');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1573','0','69712',NULL,'Ji-Kun');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('421','0','72699',NULL,'Kael\'thas Sunstrider');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1304','0','73002',NULL,'Master Snowdrift');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1663','0','74347',NULL,'Mordresh Fire Eye');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1666','0','74434',NULL,'Amnennar the Coldbringer');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1664','0','74435',NULL,'Mushlump');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1659','0','74462',NULL,'Warlord Ramtusk');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1665','0','74875',NULL,'Death Speaker Blackthorn');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('438','0','74948',NULL,'Roogug');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1656','0','75001',NULL,'Hunter Bonetusk');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','75028',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','75119',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1660','0','75247',NULL,'Groyat, the Blind Hunter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','75250',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1660','0','75292',NULL,'Groyat, the Blind Hunter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('256','0','75339',NULL,'Blackheart the Inciter');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1785','0','75357',NULL,'Iron Reaver');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','75392',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('257','0','75397',NULL,'Grandmaster Vorpil');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','76816',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','77581',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','79537',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','79638',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('406','0','79702',NULL,'Keli\'dan the Breaker');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','79769',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','80073',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('253','0','80648',NULL,'Anzu');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('254','0','80815',NULL,'Talon King Ikiss');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('1770','0','81535',NULL,'Tarlna the Ageless');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','81813',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','82668',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('230','0','83540',NULL,'Ring of Law');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('788','0','83731',NULL,'Edge of Madness');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','84974',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('253','0','85614',NULL,'Anzu');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('253','0','85615',NULL,'Anzu');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('253','0','85639',NULL,'Anzu');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('253','0','86355',NULL,'Anzu');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('836','0','87388',NULL,'Krick');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('381','0','87403',NULL,'Crowd Pummeler 9-60');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('255','0','87576',NULL,'Ambassador Hellmaw');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('246','0','88728',NULL,'Shirrak the Dead Watcher');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','88972',NULL,'Exarch Maladaar');
insert into `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `comment`) values('247','0','90179',NULL,'Exarch Maladaar');
