INSERT INTO `battlepay_product_group` (GroupID, NAME, IconFileDataID, DisplayType, Ordering) VALUES (1, "Mount", 939379, 0, 1);

SET @PRODUCTID := COALESCE((SELECT MAX(ProductID) FROM battlepay_product), 0) + 1;
SET @ORDER := COALESCE((SELECT MAX(Ordering) FROM battlepay_shop_entry WHERE GroupID = 1), 0) + 1;
SET @DISPLAYINFOID := COALESCE((SELECT MAX(DisplayInfoId) FROM battlepay_display_info), 0) + 1;

INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,104246,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,51482,0,"Reins of the Kor'kron War Wolf", "","", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,21176,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,15676,0,"Black Qiraji Resonating Crystal", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,76755,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,39530,0,"Tyrael's Charger", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,44164,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,28040,0,"Reins of the Black Proto-Drake", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,54811,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,31958,0,"Celestial Steed", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,69846,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,38260,0,"Winged Guardian", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,78924,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,40029,0,"Heart of the Aspects", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,100,100,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,92724,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,46729,0,"Swift Windsteed", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,95341,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,48020,0,"Armored Bloodwing", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,97989,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,48714,0,"Enchanted Fey Dragon", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,107951,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,53038,0,"Iron Skyreaver", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,150,150,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,112326,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,55896,0,"Warforged Nightmare", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,150,150,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,112327,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,55907,0,"Grinning Reaver", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,109013,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,53774,0,"Reins of the Dread Raven", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,100,100,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,49283,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,21973,0,"Reins of the Spectral Tiger", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,150,150,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,54860,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,31992,0,"X-53 Touring Rocket", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,116669,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,61484,0,"Armored Razorback", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,116658,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,53307,0,"Tundra Icehoof", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,116769,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,59746,0,"Mudback Riverbeast", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,116780,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,59536,0,"Warsong Direfang", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,98618,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,48931,0,"Hearthsteed", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,83086,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,42498,0,"Heart of the Nightwing", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,150,150,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,90710,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,45521,0,"Reins of the Ashen Pandaren Phoenix", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,135,150,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,115484,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,58772,0,"Core Hound Chain", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,160,250,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,122469,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,62148,0,"Mystic Runesaber", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,130,130,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,69230,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,38046,0,"Corrupted Egg of Millagazor", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,125,125,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,118515,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,61363,0,"Cindermane Charger", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
INSERT INTO `battlepay_shop_entry` (GroupID, ProductID, Ordering, Flags, BannerType, DisplayInfoID) VALUES (1,@PRODUCTID, @ORDER, 0, 0, 0);
INSERT INTO `battlepay_product` (ProductID, NormalPriceFixedPoint, CurrentPriceFixedPoint, TYPE, ChoiceType, Flags, DisplayInfoID) VALUES (@PRODUCTID,100,100,0,2,47,@DISPLAYINFOID);
INSERT INTO `battlepay_product_item` (ProductID, ItemID, Quantity, DisplayID, PetResult) VALUES (@PRODUCTID,76889,1,0,0);
INSERT INTO `battlepay_display_info` (DisplayInfoId, CreatureDisplayInfoID, FileDataID, Name1, Name2, Name3, Flags) VALUES (@DISPLAYINFOID,39546,0,"Spectral Gryphon", '',"", 0);
SET @PRODUCTID := @PRODUCTID + 1;
SET @ORDER := @ORDER + 1;
SET @DISPLAYINFOID := @DISPLAYINFOID + 1;
