SET NAMES utf8;

DELETE FROM mount WHERE ID IN (611, 622);
INSERT INTO mount VALUES
(611, 230, 59324, 0, 'Tundra Icehoof', 'A translucent layer of down hair covers this breed''s leathery hide, acting as the perfect insulation for cold environments.', '|cFFFFD200Drop:|r Vengeance, Deathtalon, Terrorfist, Doomroller|n|cFFFFD200Zone:|r Tanaan Jungle|n', 0, 171619, 0, 19865),
(622, 230, 59346, 0, 'Armored Razorback', 'Never... ever... EVER... let it smell bacon on you.', '|cFFFFD200Drop:|r Vengeance, Deathtalon, Terrorfist, Doomroller|n|cFFFFD200Zone:|r Tanaan Jungle|n', 0, 171630, 0, 19865);

DELETE FROM mount_locale WHERE ID IN (611, 622);
INSERT INTO mount_locale (ID, Name_frFR, Name_deDE, Name_esES, Name_esMX, Name_ruRU, Description_frFR, Description_deDE, Description_esES, Description_esMX, Description_ruRU, Icon_frFR, Icon_deDE, Icon_esES, Icon_esMX, Icon_ruRU) VALUES
(611, 'Sabot-glacé de la toundra', 'Tundraeishuf', 'Uñagélida de la tundra', 'Uñagélida de la tundra', 'Тундровый ледяной копытень', 'La couche translucide de poils qui recouvre la peau de cet animal agit comme un isolant et le protège des environnements particulièrement froids.', 'Das durchscheinende Unterfell dieser Art ist eine perfekte Isolierung für den Einsatz in kalten Umgebungen.', 'Una capa translúcida de mechones de pelo cubre el pellejo de cuero de esta raza y actúa como un perfecto aislante para los entornos fríos.', 'Una capa translúcida de mechones de pelo cubre el pellejo de cuero de esta raza y actúa como un perfecto aislante para los entornos fríos.', 'Прочную шкуру этого зверя покрывает слой полупрозрачного пуха, который идеально защищает от холода.', '|cFFFFD200Drop:|r Vengeance, Serres-mort, Poing-de-terreur, Compresseur funeste|n|cFFFFD200Zone:|r Jungle de Tanaan|n', '|cFFFFD200Drop:|r Rache, Todeskralle, Terrorfaust, Verdammniswalze|n|cFFFFD200Zone:|r Tanaandschungel|n', '|cFFFFD200Drop:|r Venganza, Garramuerte, Horropuño, Fatalitas|n|cFFFFD200Zone:|r Selva de Tanaan|n', '|cFFFFD200Drop:|r Venganza, Garramuerte, Horropuño, Fatalitas|n|cFFFFD200Zone:|r Selva de Tanaan|n', '|cFFFFD200Drop:|r Воздаяние, Коготь Смерти, Кулак Страха, Пушка Смерти|n|cFFFFD200Zone:|r Танаанские джунгли|n'),
(622, 'Tranchedos cuirassé', 'Gepanzerter Klingenrücken', 'Picovaja blindado', 'Picovaja blindado', 'Бронированный шипастый кабан', 'Ne... surtout... JAMAIS... les approcher quand vous sentez le bacon.', 'Passt bloß auf, dass er... NIEMALS... Schinken in Eurer Tasche riecht.', 'Nunca... nunca... JAMÁS dejes que huela que llevas panceta.', 'Nunca... nunca... JAMÁS dejes que huela que llevas panceta.', 'Никогда... никогда... НИКОГДА... не давайте ему учуять, что вы ели бекон.', '|cFFFFD200Drop:|r Vengeance, Serres-mort, Poing-de-terreur, Compresseur funeste|n|cFFFFD200Zone:|r Jungle de Tanaan|n', '|cFFFFD200Drop:|r Rache, Todeskralle, Terrorfaust, Verdammniswalze|n|cFFFFD200Zone:|r Tanaandschungel|n', '|cFFFFD200Drop:|r Venganza, Garramuerte, Horropuño, Fatalitas|n|cFFFFD200Zone:|r Selva de Tanaan|n', '|cFFFFD200Drop:|r Venganza, Garramuerte, Horropuño, Fatalitas|n|cFFFFD200Zone:|r Selva de Tanaan|n', '|cFFFFD200Drop:|r Воздаяние, Коготь Смерти, Кулак Страха, Пушка Смерти|n|cFFFFD200Zone:|r Танаанские джунгли|n');

DELETE FROM _hotfixs WHERE Entry IN (611, 622) AND HASH = 2524150337;
INSERT INTO _hotfixs (Entry, HASH, DATE, COMMENT) VALUES
(611, 2524150337, 1446459321, 'Mount'),
(622, 2524150337, 1446459321, 'Mount');