REPLACE INTO gossip_menu (entry, text_id) VALUES(10188, 14128);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(10188, 0, 1, "Je voudrais regarder vos articles.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(10362, 16705);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(10362, 0, 3, "Entraînez-moi.", 0, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(10362, 1, 1, "Laissez-moi jeter un coup d'œil sur vos marchandises.", 1, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17076, 25090);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17076, 0, 3, "Apprenez-moi le minage.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17086, 25100);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17086, 0, 3, "Apprenez-moi l'archéologie.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17126, 25172);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17126, 0, 1, "Laissez-moi jeter un coup d'œil sur vos marchandises.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17128, 25174);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17128, 0, 5, "Faites de cette auberge votre foyer.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17232, 25478);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17232, 0, 3, "Apprenez-moi l'herboristerie.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17233, 25480);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17233, 0, 1, "Laissez-moi jeter un coup d'œil sur vos marchandises.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17301, 25654);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17301, 0, 0, "Comment puis-je devenir dresseur de mascottes ?", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17313, 25685);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17313, 0, 1, "J'aimerais vous acheter quelque chose.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17376, 25829);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 0, 0, "Hôtel des ventes", 0, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 1, 0, "Banque", 1, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 2, 0, "Maître de vol", 2, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 3, 0, "Auberge", 3, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 4, 0, "Boîte aux lettres", 4, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 5, 0, "Portails", 5, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 6, 0, "Maître des mascottes de combat", 6, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 7, 0, "Maître de métier", 7, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 8, 0, "Maître des écuries", 8, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 9, 0, "Transmogrification & chambre du Vide", 9, 0, 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 10, 0, "Marchand", 10, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(6944, 7778);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(6944, 0, 2, "Montrez-moi où je peux voler.", 0, 0, 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(10188, 14128);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(10188, 0, 1, "Je voudrais regarder vos articles.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(10362, 16705);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(10362, 0, 3, "Entraînez-moi.", 0, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(10362, 1, 1, "Laissez-moi jeter un coup d'œil sur vos marchandises.", 1, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(16680, 25419);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16680, 0, 0, "Prenez tous mes fragments dartéfacts !", 0, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16680, 1, 0, "Combien de fragments dartéfacts avons-nous rassemblés ?", 1, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16680, 2, 0, "À quoi sert Kronus ?", 2, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(16776, 24394);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16776, 0, 0, "Prenez tous mes fragments dartéfacts !", 0, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16776, 1, 0, "Combien de fragments dartéfacts avons-nous rassemblés ?", 1, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16776, 2, 0, "Quel est le rôle des Chevaucheurs de loups ?", 2, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(16806, 24435);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16806, 0, 0, "Prenez tous mes fragments dartéfacts !", 0, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16806, 1, 0, "Combien de fragments dartéfacts avons-nous rassemblés ?", 1, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16806, 2, 0, "À quoi servent les portails de mage ?", 2, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(16809, 24438);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16809, 0, 0, "Prenez tous mes fragments dartéfacts !", 0, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16809, 1, 0, "Combien de fragments dartéfacts avons-nous rassemblés ?", 1, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(16809, 2, 0, "À quoi servent les portes de démoniste ?", 2, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17001, 24748);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17001, 0, 1, "Jaimerais vous acheter quelque chose.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17049, 24983);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17049, 0, 12, "J'aimerais utiliser l'écurie.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17076, 25090);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17076, 0, 3, "Apprenez-moi le minage.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17086, 25100);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17086, 0, 3, "Apprenez-moi larchéologie.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17126, 25172);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17126, 0, 1, "Laissez-moi jeter un coup d'œil sur vos marchandises.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17128, 25174);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17128, 0, 5, "Faites de cette auberge votre foyer.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17130, 25176);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17130, 0, 3, "Apprenez-moi l'enchantement.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17152, 25243);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17152, 0, 3, "Apprenez-moi le dépeçage.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17153, 25244);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17153, 0, 3, "Apprenez-moi la forge.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17157, 25249);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17157, 0, 3, "Apprenez-moi la pêche.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17187, 25280);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17187, 0, 0, "Comment puis-je devenir dresseuse de mascottes ?", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17232, 25478);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17232, 0, 3, "Apprenez-moi l'herboristerie.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17233, 25480);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17233, 0, 1, "Laissez-moi jeter un coup d'œil sur vos marchandises.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17245, 25519);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17245, 0, 1, "Laissez-moi jeter un coup d'œil sur vos marchandises.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17301, 25654);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17301, 0, 0, "Comment puis-je devenir dresseur de mascottes ?", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17312, 25685);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17312, 0, 1, "Jaimerais vous acheter quelque chose.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17313, 25685);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17313, 0, 1, "Jaimerais vous acheter quelque chose.", 0, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17334, 25786);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 0, 0, "Hôtel des ventes", 0, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 1, 0, "Banque", 1, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 2, 0, "Maître de vol", 2, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 3, 0, "Auberge", 3, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 4, 0, "Boîte aux lettres", 4, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 5, 0, "Portails", 5, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 6, 0, "Maître des mascottes de combat", 6, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 7, 0, "Maître de métier", 7, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 8, 0, "Maître des écuries", 8, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 9, 0, "Transmogrification & chambre du Vide", 9, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17334, 10, 0, "Marchand", 10, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(17376, 25829);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 0, 0, "Hôtel des ventes", 0, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 1, 0, "Banque", 1, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 2, 0, "Maître de vol", 2, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 3, 0, "Auberge", 3, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 4, 0, "Boîte aux lettres", 4, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 5, 0, "Portails", 5, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 6, 0, "Maître des mascottes de combat", 6, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 7, 0, "Maître de métier", 7, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 8, 0, "Maître des écuries", 8, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 9, 0, "Transmogrification & chambre du Vide", 9, , 0, "");
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(17376, 10, 0, "Marchand", 10, , 0, "");
REPLACE INTO gossip_menu (entry, text_id) VALUES(6944, 7778);
REPLACE INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, box_coded, box_money, box_text) VALUES(6944, 0, 2, "Montrez-moi où je peux voler.", 0, , 0, "");