#!/bin/bash

### CONFIGURATION ###
server_name="6.2.3"
server_domain="firestorm-servers.com"
slack_hook_urls=("https://hooks.slack.com/services/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")
force_asan_mode=1
normal_build_mode=Debug
### CONFIGURATION END ###

function sendToSlack {
    msg=$1
    color=$2

    for hook_url in "${slack_hook_urls[@]}"
    do
        curl -X POST \
             --data-urlencode 'payload={"attachments": [{"pretext": "*'"$server_name"'*", "text": "'"$msg"'", "color": "'"$color"'", "mrkdwn_in": ["pretext", "text"]}]}' \
             $hook_url
    done
}

last_crash_date=0
crash_number=0
asan_mode=0
realm_name=$(dirname $(pwd) | cut -d '/' -f3)

ulimit -n 4096

while :
do
    day=$(date +%u) #return 1 is monday
    if [ $day -eq 1 ] || [ $force_asan_mode -eq 1 ]; then
        asan_mode=1
    fi

    if [ $asan_mode -eq 1 ]; then
        # for options see https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer
        ASAN_OPTIONS=detect_leaks=0
        ./worldserver_Asan 2>&1 | asan_symbolize -d > backtrace.log
    else
        gdb -batch -x=crashreport.gdb ./worldserver_$normal_build_mode
    fi

    is_killed=`egrep 'SIGTERM|SIGINT' backtrace.log`
    if [ -n "$is_killed" ]; then
        # process has been killed so don't do anything, just restart quietly
        continue
    fi

    # check if it's a shutdown or restart
    is_ok=$(grep -oP "(?:exited normally|exited with code 02)" backtrace.log)
    if [ -z "$is_ok" ]; then
        crashlog_filename="crashdump_$(date +\%Y-\%m-\%d-\%H-\%M-\%S).crashlog"
        crashlog_link="http://ptr.$server_domain/crashlogs_ashran_pig_79879/$realm_name/$crashlog_filename"

        if [ $last_crash_date -ne 0 ]; then
            # reset crash_number when last crash >= 2 min
            crash_diff=$(( ( $(date +%s) - $last_crash_date ) / 60 ))
            if [ $crash_diff -ge 2 ]; then
                crash_number=0
            fi
        fi

        last_crash_date=$(date +%s)
        ((crash_number++))

        cat backtrace_mysql.log >> backtrace.log
        mv backtrace.log ../crashlogs/$crashlog_filename

        if [ $asan_mode -eq 0 ]; then
            crash_location=$(grep -oP 'in \K(.*) at' ../crashlogs/$crashlog_filename | head -n 1)
            sendToSlack "_ $realm_name _ crashed in \`$crash_location\` <$crashlog_link|Show more...>" "danger"
        else
            sendToSlack "_ $realm_name _ crashed with ASan <$crashlog_link|Show more...>" "danger"
        fi

        if [ $crash_number -ge 5 ]; then
            sendToSlack "<!channel> the realm _ $realm_name _ is chain crashing, restarter killed to avoid spam." "danger"
            kill -9 $$ # Self destruct, child too
        fi
    else
        sendToSlack "_ $realm_name _ exited normally." "good"
    fi
done
