DELETE FROM `conditions` WHERE SourceEntry = 101883;
INSERT INTO `conditions`
            (`SourceTypeOrReferenceId`,
             `SourceGroup`,
             `SourceEntry`,
             `SourceId`,
             `ElseGroup`,
             `ConditionTypeOrReference`,
             `ConditionTarget`,
             `ConditionValue1`,
             `ConditionValue2`,
             `ConditionValue3`,
             `NegativeCondition`,
             `ErrorTextId`,
             `ScriptName`,
             `Comment`)
VALUES ('17',
        '0',
        '101883',
        '0',
        '0',
        '4',
        '0',
        '5861',
        '0',
        '0',
        '0',
        '0',
        '',
        'Heal Injured Carnie only usable on ShadowMoon');