delete from spell_loot_template where entry = 111672;
delete from spell_loot_template where entry = 155306;
delete from spell_loot_template where entry = 155307;
delete from spell_loot_template where entry = 168835;
delete from spell_loot_template where entry = 169092;
delete from spell_loot_template where entry = 175093;
delete from spell_loot_template where entry = 175094;
delete from spell_loot_template where entry = 177346;
delete from spell_loot_template where entry = 177453;
delete from spell_loot_template where entry = 178531;
delete from spell_loot_template where entry = 178533;

insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('111672','109142','100','1','0','20','35','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('155306','111598','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('155306','120354','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('155307','111600','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('155307','120356','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('168835','113262','25','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('168835','113264','25','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('169092','113261','25','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('169092','113264','25','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('175093','118093','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('175094','118094','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('177346','119330','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('177346','120353','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('177453','111599','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('177453','120355','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('178531','120151','100','1','0','1','1','');
insert into `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`, `itemBonuses`) values('178533','118065','100','1','0','1','1','');
